### ISSUE TITLE
E4 Timeout on esp8266

### ISSUE THREAD

**Issue by 4lfaBrav0** [emelianov/modbus-esp8266#102]
Hi, first of all thank you very much for this amazing library!
I was trying to read multiple registers; mostly it works but sometimes it happens that it returns E4 timeout.
I tried both the 3.0.6 an the master but it seems to have the same behaviour. I also tried to change speed from 9600bps to 57600 but it's almost the same and I tried to switch TTL/RS485 interface but nothing. 
I will need to make a request per second so, for to allow immediate retry in case of error, I lowered the MODBUSRTU_TIMEOUT to 200, and usually it works fine but I'm not sure if it's made in proper way. I also tried to change the peripheral  (an energy monitor) data answer delay to 100ms but error is the same.
What can you suggest to try solve the issue? Thanks

Here the sample code:
```c++
#include <ModbusRTU.h>
#include <SoftwareSerial.h>

SoftwareSerial rs485;
ModbusRTU mb;

bool flag = false;

bool cb(Modbus::ResultCode event, uint16_t transactionId, void* data) {
  if (event==0){
    Serial.println("1");
    flag = true;
  }else {
    Serial.printf("0 Result code: %02X - retrying...\n", event);
    flag = false;
  }
  return true;
}

void setup() {
  Serial.begin(115200);
  rs485.begin(57600, SWSERIAL_8N1, 4, 5);
  mb.begin(&rs485);
  mb.master();
}

void loop() {
  uint16_t regs[12];

  while (flag == false){
    if (!mb.slave()) {
      mb.readHreg(1, 358, regs, 12, cb);
      while (mb.slave()){
        Serial.print(".");
        mb.task();
        delay(10);          
      }
    }
  }
  flag = false;  
  delay(500);
}
```

Serial output (with MODBUSRTU_TIMEOUT  set to default 1000) :
14:30:11.401 -> ...1
14:30:11.912 -> ...1
.
.
20:34:19.538 -> .....................................................................................................0 Result code: E4 - retrying...
20:34:20.562 -> ...1
20:34:20.069 -> ...1
.
.
20:35:12.236 -> .....................................................................................................0 Result code: E4 - retrying...
20:35:13.259 -> ...1
20:35:13.771 -> ...1
.
.
20:39:08.591 -> ...1
20:39:08.103 -> .....................................................................................................0 Result code: E4 - retrying...
20:39:09.127 -> ...1
20:39:10.674 -> .....................................................................................................0 Result code: E4 - retrying...
20:39:11.699 -> ...1
20:39:12.211 -> ...1

**Comment by emelianov** [comment]
Hello,
I seems to me there is hardware problem. In general with my hardware i was unable to achieve stable connection with auto RX/TX switching RS-485 transceiver at hire than 9600 (i suspect power stability on ESP side was the reason).
So suggested way to escape timeouts:
1. Use additional power source stabilisation on ESP side.
2. Replace RS-485 transceiver on ESP side to something alike MAX-485 with additional RE/DE control pin.
3. Try to use HardwareSerial (Serial that is typically used for debug) for Modbus connection.
