### ISSUE TITLE
ModbusTCP Ethernet ESP32 on enc28j60

### ISSUE THREAD

**Issue by oscarquiroz94** [emelianov/modbus-esp8266#103]
Dear.
Thank you for your effort on this library, it is very helpful for everyone.
I have a question, I know that this library works with W5x00. It is possible to use enc68j60 chip?

**Comment by emelianov** [comment]
It's [reported](https://github.com/emelianov/modbus-esp8266/issues/101#issuecomment-752189158) that the library is working with enc28j60 using [UIPEthernet library](https://github.com/UIPEthernet/UIPEthernet).

**Comment by oscarquiroz94** [comment]
I will try. Thank you.

**Comment by mlednicky** [comment]
Hello, 

I am trying to use this library for ESP32 and ENC28j60, but it doesnt work for me. 

![image](https://user-images.githubusercontent.com/79508273/178735205-64e1c811-8791-47a8-927c-066033a1ef73.png)

Ping works, internally the registers works but I can not access registers from the outside by Modbus Master simulator. 

Do you have any idea what could be the problem?

Thank you.

**Comment by emelianov** [comment]
That is the error type: timeout or something else?

**Comment by mlednicky** [comment]
I tried to connect by two different clients: 
Radzio modbus master simulator says: "Modbus message timeout"
ProFace HMI: TCP connection open error
...the same as when nothing is connected.

I also tried to use your library as Modbus Client, it works fine with the same hardware/connection. 
The only difference I noticed is:
 
When ESP32 used as client, keyword  "client()" turns orange, 
![image](https://user-images.githubusercontent.com/79508273/179166730-23908c6a-8819-401f-b7c8-e2ed3e773823.png)

But when used as server, keyword "server()" stays black. 
![image](https://user-images.githubusercontent.com/79508273/179166678-22bfccdc-3d1e-49af-89b6-fb210fcc89ef.png)

**Comment by emelianov** [comment]
It looks like was a bug.
Try fixed code code from master branch ([99e2145](https://github.com/emelianov/modbus-esp8266/commit/99e2145d0297c2cff694e487ba708726900f6524))

**Comment by mlednicky** [comment]
I updated the library, but its the same for me.

**Comment by emelianov** [comment]
Probably this addressed to you issue: https://github.com/UIPEthernet/UIPEthernet/issues/155

Also try [EthernetENC library](https://github.com/JAndrassy/EthernetENC) instead.
