### ISSUE TITLE
Modbus read Master

### ISSUE THREAD

**Issue by DiegoVGFB** [emelianov/modbus-esp8266#11]
Hi, where I can find an example of read a register from a MasterPLC and conver my ESP  as a Slave?

**Comment by emelianov** [comment]
Just for sure: You have 3d-party PCL with Modbus Master functionality and want get data from Slave ESP.
That case you may take a look *HoldingReg* example for ESP.
From PCL probably you may need to play with register number depending on zerro or one numeration base is used by the PCL.

**Comment by emelianov** [comment]
It depends on PLC. I'm afraid there is no quick answer.
