### ISSUE TITLE
pullHreg fails to compile

### ISSUE THREAD

**Issue by rzylius** [emelianov/modbus-esp8266#112]
hi,

I am trying to compile code with rtu master instance pullHreg function and receive an error. So for testing I tried to compile example code https://github.com/emelianov/modbus-esp8266/tree/master/examples/bridge

I am using dev branch 4.0
and get error:

> In file included from C:\GITHUB\arduino-home\libraries\modbus-esp8266-master\src/ModbusTCP.h:14:0,
                 from C:\GITHUB\arduino-home\libraries\modbus-esp8266-master\src/ModbusIP_ESP8266.h:9,
                 from C:\GITHUB\arduino-home\_modbus_bridge_generic\_modbus_bridge_generic.ino:12:
C:\GITHUB\arduino-home\libraries\modbus-esp8266-master\src/ModbusAPI.h: In instantiation of 'uint16_t ModbusAPI<T>::pullHreg(TYPEID, uint16_t, uint16_t, uint16_t, cbTransaction, uint8_t) [with TYPEID = int; T = ModbusRTUTemplate; uint16_t = short unsigned int; cbTransaction = std::function<bool(Modbus::ResultCode, short unsigned int, void*)>; uint8_t = unsigned char]':
C:\GITHUB\arduino-home\_modbus_bridge_generic\_modbus_bridge_generic.ino:48:43:   required from here
C:\GITHUB\arduino-home\libraries\modbus-esp8266-master\src/ModbusAPI.h:172:19: error: call of overloaded 'addReg(TAddress, int, uint16_t&)' is ambiguous
 #define ADDREG(R) this->addReg(R(to), 0, numregs);
                   ^
C:\GITHUB\arduino-home\libraries\modbus-esp8266-master\src/ModbusAPI.h:181:2: note: in expansion of macro 'ADDREG'
  ADDREG(REG) \
  ^
C:\GITHUB\arduino-home\libraries\modbus-esp8266-master\src/ModbusAPI.h:187:1: note: in expansion of macro 'IMPLEMENT_PULL'
 IMPLEMENT_PULL(pullHreg, HREG, FC_READ_REGS, 0x007D)
 ^
C:\GITHUB\arduino-home\libraries\modbus-esp8266-master\src/ModbusAPI.h:172:19: note: candidates are:
 #define ADDREG(R) this->addReg(R(to), 0, numregs);
                   ^
C:\GITHUB\arduino-home\libraries\modbus-esp8266-master\src/ModbusAPI.h:181:2: note: in expansion of macro 'ADDREG'
  ADDREG(REG) \
  ^
C:\GITHUB\arduino-home\libraries\modbus-esp8266-master\src/ModbusAPI.h:187:1: note: in expansion of macro 'IMPLEMENT_PULL'
 IMPLEMENT_PULL(pullHreg, HREG, FC_READ_REGS, 0x007D)
 ^
In file included from C:\GITHUB\arduino-home\libraries\modbus-esp8266-master\src/ModbusAPI.h:8:0,
                 from C:\GITHUB\arduino-home\libraries\modbus-esp8266-master\src/ModbusTCP.h:14,
                 from C:\GITHUB\arduino-home\libraries\modbus-esp8266-master\src/ModbusIP_ESP8266.h:9,
                 from C:\GITHUB\arduino-home\_modbus_bridge_generic\_modbus_bridge_generic.ino:12:
C:\GITHUB\arduino-home\libraries\modbus-esp8266-master\src/Modbus.h:219:14: note: bool Modbus::addReg(TAddress, uint16_t, uint16_t)
         bool addReg(TAddress address, uint16_t value = 0, uint16_t numregs = 1);
              ^
C:\GITHUB\arduino-home\libraries\modbus-esp8266-master\src/Modbus.h:223:14: note: bool Modbus::addReg(TAddress, uint16_t*, uint16_t)
         bool addReg(TAddress address, uint16_t* value, uint16_t numregs = 1);
              ^
Using library ESP8266WiFi at version 1.0 in folder: C:\Users\Rimantas\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi 
Using library modbus-esp8266-master at version 4.0.0-DEV in folder: C:\GITHUB\arduino-home\libraries\modbus-esp8266-master 
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

I have tested with 3.0.7 branch compiles with no problems.

**Comment by emelianov** [comment]
Fixed: c65b059
