### ISSUE TITLE
error: 'class ModbusIP' has no member named 'server'

### ISSUE THREAD

**Issue by stefunkk** [emelianov/modbus-esp8266#113]
Hello,

I'm trying to setup esp8266 as a slave and read data, but with example 
https://github.com/emelianov/modbus-esp8266/blob/master/examples/TCP-ESP/server/server.ino

I'm getting:

src\main.cpp: In function 'void setup()':
src\main.cpp:43:6: error: 'class ModbusIP' has no member named 'server'
   43 |   mb.server();
      |      ^~~~~~

**Comment by stefunkk** [comment]
On Arduino works,

**Comment by stefunkk** [comment]
https://ibb.co/MG5VZMg - any ideas why i cant run example from https://github.com/emelianov/modbus-esp8266/blob/master/examples/TCP-ESP/server/server.ino ?

**Comment by emelianov** [comment]
> https://ibb.co/MG5VZMg - any ideas why i cant run example from https://github.com/emelianov/modbus-esp8266/blob/master/examples/TCP-ESP/server/server.ino ?

Read Hreg 101 as you client seems to use 1-based addressing
