### ISSUE TITLE
How many maximum of holding registers ?

### ISSUE THREAD

**Issue by hall1235** [emelianov/modbus-esp8266#118]
Hello.

I have tried to use a lot of holding registers then, I got the maximum of holding registers. the result is 4095 of holding registers after that esp32 will reboot itself. Can I change the maximum of holding register to 65535.

Thank you so much.

**Comment by emelianov** [comment]
Looks like a bug in STL's std::vector
As workaround disable use of STL by commenting
```c
#define MODBUS_USE_STL
```
in *ModbusSettings.h*

**Comment by hall1235** [comment]
**Thank you so much.** @emelianov
