### ISSUE TITLE
Getting Illegal data address Error

### ISSUE THREAD

**Issue by d-hardik** [emelianov/modbus-esp8266#121]
i am able to connect to Modbus TCP-server created on ESP,but getting Illegal data address error. 
what can be reason ?
![image](https://user-images.githubusercontent.com/26281901/114700574-4caf7600-9d3f-11eb-9151-6dbb72691a30.png)

**Comment by emelianov** [comment]
Hi,
Probably the Modbus client assumes 1-based addressing. Try to read Hreg 101.

**Comment by d-hardik** [comment]
ok so offset 100 means?
also getting same error for 1

**Comment by d-hardik** [comment]
which tool you propose to test the modbus, and also setting for the example codes

**Comment by emelianov** [comment]
Left TEST_HREG = 100 and try to read 100 or 101 registers from client side.
Note that basing the screenshot you are trying to read 0x100 **HEX** register.

**Comment by d-hardik** [comment]
ok solved with Decimal Offset
Thank you so much Alexander for such a quick response
 
![image](https://user-images.githubusercontent.com/26281901/114720760-ec77fe80-9d55-11eb-8feb-d54c8ebb078a.png)
