### ISSUE TITLE
Check Communication modbusRTU

### ISSUE THREAD

**Issue by hall1235** [emelianov/modbus-esp8266#126]
Hello.

I have one master and two slaves. Then, I use master read registers from slave via modbusRTU.

How can I check the communication of slave devices which is still connected?

Thank you so much.

**Comment by emelianov** [comment]
If slave device become unavailable you will just starts getting timeout errors on read/write requests. It's the only check possible.

**Comment by hall1235** [comment]
Thank you so much @emelianov
