### ISSUE TITLE
Question: Correct handling of call back functions

### ISSUE THREAD

**Issue by abishur** [emelianov/modbus-esp8266#127]
I've just started using this excellent library and had a question on the correct usage of call back functions.   In the example for IP-server-MassOperations it shows for the cbRead function a basic test is done to make sure that the register being read by another device actually exists as one you configured, however in the cbWrite function it just writes the new value to the register.

Would it be better to put the same logic check in cbWrite in case a device tries to write to a register that doesn't exists?

Also, my understanding is that these two function are automatically called when a remote device attempts to read from or write to a coil without anything in the loop routine, is that correct?

**Comment by emelianov** [comment]
In this particular case register address checking making sense in terms of controlling array out-of-bounce (if someone will modify this code).
Indeed no checking of is required as the library have performed all required checks before calling the callback.
