### ISSUE TITLE
Timeout problem in Modbus RTU communication

### ISSUE THREAD

**Issue by GlossyP** [emelianov/modbus-esp8266#128]
Hello everyone !

I'm faced with a modbus RTU communication issue. I use a WeMos D1 R2 card as the master. The slave being an Hukseflux pyranometer. The data I'm interested in is contained by input register address 2.

Here is my test code: 

`#include <ModbusRTU.h>
#include <SoftwareSerial.h>

SoftwareSerial S1(D2,D3);
ModbusRTU mb;

bool cbRequete(Modbus::ResultCode res, uint16_t trans, void *don)
{
  S1.printf("Resultat: 0x%02X", res);
  S1.println();
  return true;
}

void setup()
{
  S1.begin(19200);
  Serial.begin(19200, SERIAL_8E1);
  mb.begin(&Serial);
  mb.master();
}

void loop()
{
  double puis, temp;
  uint16_t n, w[2];

  if (!mb.slave())
  {
    n = mb.readIreg(5, 2, w, 2, cbRequete);
    while (mb.slave())
    {
      S1.print('.');
      mb.task();
      delay(10);
    }
    S1.println(n);
    puis = w[0] * 65536 + w[1];
    puis /= 100.0;
    S1.println(puis);
   }
  delay(10000);
}`

All my attempts until now failed ! This systematically ends up with a timeout code E4 returned by the callback function cbRequete.

Any help would be greatly appreciated.

P.S: I use a stabilized power source.

**Comment by emelianov** [comment]
Hi,

Try to use different version of SoftwareSerial library or even HardwareSerial (you need completely disable debug output o remap it to Serial1)
