### ISSUE TITLE
Running on Arduino Mega 2560 + W5100

### ISSUE THREAD

**Issue by piranha771** [emelianov/modbus-esp8266#129]
Hello great lib,

I have first used a ESP8266 but migrated to an Arduino Mega 2560 because I needed more AD-pins.
I modified the lib so that it uses Ethernet (W5100 shield) instead of Wifi. It now works most of the time.
But now my HMI-Display does not connect reliably to the Arduino modbus server when Arduino is already running for some time,

My question is: is it okay to use this lib with MEGA2560 in the first place? Or should I use another project, because this will only reliably work on ESP chips?
I like this library for it's ease with callbacks.

**Comment by emelianov** [comment]
Hello,

The library form master branch should work with mega + ethernet (v2.0.0) without any modifications.
If not and you had to make some modifications to make the library working can you share it?
