### ISSUE TITLE
Byte order with float32

### ISSUE THREAD

**Issue by bidyutper** [emelianov/modbus-esp8266#134]
![Untitled](https://user-images.githubusercontent.com/16462057/125412004-20f26980-e3dc-11eb-9aa1-f6834642cd0b.png)

How to get float32 value. 
Set slave as per attached image.
Master running on NodeMCU not showing set value in slave

      uint32_t value32;
      mb.readHreg(SLAVE_ID, 8, (uint16_t*)&value32, 2, cb);
      value32 = (value32>>16) | (value32<<16); // Uncomment for words swap
      Serial.printf("voltage = %.2f\n", value32);

**Comment by bidyutper** [comment]
Issue resolved.

**Comment by mazur866** [comment]
hello, can you share your solution ?? Thank you for your help
