### ISSUE TITLE
ESP32 ModbusRTU begin() with txPin

### ISSUE THREAD

**Issue by fglaria** [emelianov/modbus-esp8266#139]
On description, it shows that there are 3 ways of calling begin() function:

```c
bool begin(SoftwareSerial* port, int16_t txPin=-1, bool direct=true);
bool begin(HardwareSerial* port, int16_t txPin=-1, bool direct=true);
bool begin(Stream* port);
```

But when checking this, it shows that:

```c
#if defined(ESP8266)
    bool begin(SoftwareSerial* port, int16_t txPin=-1, bool direct=true);
#endif
    bool begin(HardwareSerial* port, int16_t txPin=-1, bool direct=true);
    bool begin(Stream* port);
```

Why there is no option for setting txPin using SoftwareSerial for ESP32?

**Comment by emelianov** [comment]
SoftwareSerial for ESP32 is supported starting from 4.0.0 (currently in pre-release state, master branch)

**Comment by fglaria** [comment]
So, for my project I could just remove the #if statements and it should work anyway?

**Comment by emelianov** [comment]
It looks like it should work this way. Also you can use current library version from master branch.

**Comment by fglaria** [comment]
I tried it, it seemed to work.
Finally I decided to use HardwareSerial instead.
I'm actually trying to fix the famous 0xE4 error, and I haven't been able to do it yet, but I'll close this issue.
