### ISSUE TITLE
bool ModbusIP::disconnect(IPAddress ip) returns nothing

### ISSUE THREAD

**Issue by Tomat7** [emelianov/modbus-esp8266#14]
Got compilation error on this version when tried to compile on VS17+VisualMicro:
`ModbusIP_ESP8266.cpp: 410:1: error: no return statement in function returning non-void [-Werror=return-type]`
and that's TRUE :-(
`bool ModbusIP::disconnect(IPAddress ip) {
	int8_t p = getSlave(ip);
	if (p != -1) client[p]->stop();
}`

and it is compiled correctly under Arduino IDE... :-)

**Comment by emelianov** [comment]
Thanks. Fixed as part of 9cadf5d.
