### ISSUE TITLE
Rename "Server" to "Slave", "Client" to "Master"

### ISSUE THREAD

**Issue by Tomat7** [emelianov/modbus-esp8266#141]
Let's return to old Modbus ideology!

BTW..
>"The library now is compatible with all Arduino platforms"
> "Support for Ethernet library (W5x00, ENC28J60, etc)"

Is the Arduino Nano with ENC28J60 supported?

**Comment by emelianov** [comment]
> Let's return to old Modbus ideology!

It's not my war: [Modbus.org PRESS RELEASE](https://modbus.org/docs/Client-ServerPR-07-2020-final.docx.pdf)

> Is the Arduino Nano with ENC28J60 supported?

It's [reported](https://github.com/emelianov/modbus-esp8266/issues/101#issuecomment-752189158) that the library is working with enc28j60 using [UIPEthernet library](https://github.com/UIPEthernet/UIPEthernet).

I've performed some tests on Leonardo + W5100 Ethernet shield. It works.

**Comment by Tomat7** [comment]
> It's not my war: Modbus.org PRESS RELEASE
Слов нет... :(
