### ISSUE TITLE
Modbus on ESP32 over Wifi/Eth.h with LAN8720

### ISSUE THREAD

**Issue by LukasBross** [emelianov/modbus-esp8266#143]
Hi,

Is it possible to use the Eth.h from the standard ESP32 Wifi lib together with a LAN8720 phy for a Modbus TCP connection with your library? Do you have any experience with it?

https://github.com/espressif/arduino-esp32/tree/master/libraries/WiFi

Thank You.

**Comment by emelianov** [comment]
Hi,

It will work. You need just replace WiFi initialization code with Ethernet one.

**Comment by sebarch** [comment]
Hi Lukas!! Can you tell me if Modbus over Wifi/Eth.h with LAN8720 worked. Do you have any example? Thanks!!

**Comment by mxsan** [comment]
it works! 
Thx a lot!

**Comment by max195824** [comment]
Alguien tiene algun ejemplo de modbus en esp32, Eth.h con LAN8720 funcionando como servidor, desde ya se agradece.
Saludos.

**Comment by DACOSTARLC** [comment]
> it works! Thx a lot!

Friend, could you share your code that worked using the lan8720 chip with ESP32 and MODBUS TCP?

**Comment by DACOSTARLC** [comment]
> Hi,
> 
> It will work. You need just replace WiFi initialization code with Ethernet one.

Friend, could you share your code that worked using the lan8720 chip with ESP32 and MODBUS TCP?
