### ISSUE TITLE
Modbus RTU with MAX485

### ISSUE THREAD

**Issue by kuhl026** [emelianov/modbus-esp8266#149]
Hello. I'm not able to identify which pin should I use the _txPin to connect to the MAX 485. If you can send me the connection scheme of esp32 + MAX485.
Thanks.

**Comment by milen100** [comment]
It should be clearly explained in the documentation, but looking at example my guess is : 
// Create Soft Serial Port with RX and TX pins (  pin 13 to RO,  pin 15 to DI  )
 SoftwareSerial S(13, 15);

//Use pin 4 as TX enable pin
int DE_RE = 4; //D4  (02) For MAX485 chip

//Create Modbus object
ModbusRTU mb;

void setup() {
  //Initialize hard serial port with 115200 baud
  Serial.begin(115200);
  //Initialize Soft Serial(modbus) port at 9600 baud
  S.begin(9600, SWSERIAL_8N1);
  //Initiaize mb object with serial port and TX_enable pin DE_RE(4)
  mb.begin(&S, DE_RE);
  // Set it to master 
  mb.master();

 ..................

**Comment by emelianov** [comment]
Example of wiring for ESP32 is
==
Serial1.begin(9600, SERIAL_8N1, 19, 18);
mb.begin(&Serial1, 17);
==
connection should be
GPIO 19 - RO
GPIO 18 - DI
GPIO 17 - RE DE (both)
