### ISSUE TITLE
RTU Server - Multiple Slave IDs Simultaneously?

### ISSUE THREAD

**Issue by JPJrunesJPJ** [emelianov/modbus-esp8266#152]
Hello,

Thanks for sharing this amazing library, it's been working great for me so far.

I have an issue and I'm not sure if it's due to how I'm using the library, or if it is a limitation of the library:

- I'm trying to act as up to 16 different slave IDs simultaneously on Modbus RTU with an ESP32.  Each Slave ID would have its own set of registers with unique information.
- In my code, I declare two separate ModbusRTU objects: mb and mb2.
- I have their commands issued back-to-back (E.G. mb.begin(&Serial2,RXTXpin) is immediately followed by mb2.begin...).
- I've tried switching their order, whichever ModbusRTU object (and associated slave ID) is initiallized/polled first is the only one that I can perform Modbus Read Holding Register functions on.

Has anyone successfully set up multiple slave IDs with unique data on a single RTU port?

**Comment by emelianov** [comment]
Hello,

Unfortunatly it's not possible to share Serial port across multiple ModbusRTU instances. Also no API implemented to allow the library oblect instance to answer on multiple slave IDs.

Anyway it's interesting point. I'll put it to todo list.

**Comment by Tomat7** [comment]
Hello!
JPJrunesJPJ, looks like you want to hack existing RTU net with many slaves and provide fake data to master. :-)
Tell more about you project - possible you need to change design.
Ilya.

**Comment by squagle** [comment]
Hello. I am also working on this project with JPJrunesJPJ .
Emelianov; Thank you for the feedback and adding the request to the 5.0 milestone.  You have a great project.
Tomat7 & others interested.  Our hope is to use the above feature to create a modbus TCP to RTU Bridge.  I know this project already has sample code for a single slave to master bridge but I am hopeful we would be able to create a bridge to work with multiple TCP servers (slaves) to a single modbus RTU master.  The reason for this is we have an existing web enabled esp32 project with Ethernet and WiFi but an old PLC that only has Modbus RTU.   We think the best way to get there would be to have an esp32 that acts as a bridge between the new esp32 wifi project and the legacy RTU PLC.

Thanks!

**Comment by Tomat7** [comment]
> legacy RTU PLC

Does this PLC work as slave or master?
How many "legacy PLC" in your project?

**Comment by squagle** [comment]
Thanks again for the comment.

Legacy PLC acts as Modbus RTU master.  ESP32 device acts as Modbus TCP server (slaves).  My hope is we can use upto 16 instances of the esp32 device with the legacy PLC.    The bridge would be "transparent" to the Modbus RTU master PLC.  It would just "see" the esp32 Modbus TCP server (slave) as just another RTU slave.  The bridge enables to the legacy modbus RTU PLC to interact with the new ESP32 Modbus TCP devices.

**Comment by emelianov** [comment]
@squagle 
In this particular case it's better to modify the library core logic to implement this way of bridging effectively. You can e-mail me if you are interested in support.
At least only one problem exists: ESP32 is limited in simultaneous TCP connections. I'm not 100% sure but it looks like 10 for Arduino/ESP32.

**Comment by squagle** [comment]
@emelianov  Email sent.   My hope for was 16 TCP servers (slaves) but I could make do with 8.

**Comment by Merdock1** [comment]
@JPJrunesJPJ  Hello if I have managed to connect to multiple slaves but using a complementary library for the connection with RTU servers.

This is the address of the bookstore.
It only supports both reading and writing retention registers.
[](https://github.com/angeloc/simplemodbusng)

this is the code of my main
includes data transfer via websocket.

`#include <Arduino.h>
#include "VFD_ModbusIP_WebSocket.h"
#include "SimpleModbusMasterUap.h" // Master ModBus. Modified.
#include <ESP8266WiFi.h>
#include "ModbusIP_ESP8266.h"
#include <SoftwareSerial.h>
// For WebSocket
#include <ESP8266WebServer.h>
#include <WebSocketsServer.h>
#include <Ticker.h>

/*
  Modbus ESP8266/ESP32
  Simple ModbusRTU to ModbusIP bridge

  (c)2020 Alexander Emelianov (a.m.emelianov@gmail.com)
  https://github.com/emelianov/modbus-esp8266
*/

//// Se configuran los parametros de RED  ///
// Dirección IP VFD Hemoglobina 192, 1, 1, 2
IPAddress local_IP(192, 1, 1, 1);
IPAddress gateway(192, 1, 1, 1);
IPAddress subnet(255, 255, 255, 0);
IPAddress primaryDNS(192, 1, 1, 1);
IPAddress secondaryDNS(8, 8, 8, 8);
ModbusIP mb_ip_vfd;

//// WebSocket ////
// Instantiate server objects
ESP8266WebServer server(80);
WebSocketsServer webSocket = WebSocketsServer(81);

// Declare/initialize timer variables
Ticker timer;
bool read_data = false;
// Raw string literal for containing the page to be sent to clients
char webpage[] PROGMEM = R"=====(
<html>
<head>
  <script>
    var Socket;
    function init() {
      Socket = new WebSocket('ws://' + window.location.hostname + ':81/');
      Socket.onmessage = function(event){
        // receive the color data from the server
        var data = JSON.parse(event.data);
        console.log(data);
      }
    }  
  </script>
</head>
<body onload="javascript:init()">
  <h4>Websocket client served from the Sensor Board!</h4>
</body>
</html>
)=====";



///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//// Cliente Modbus RTU ///
SMM_Packet SMM_packets[SMM_TOTAL_NO_OF_PACKETS]; // Create an array of
                                                     // SMM_Packets for
                                                     // SMM_modbus_update()
SMM_packetPointer vfd_1_packet_00 = &SMM_packets[VFD_1_PACKET_0]; // Create a SMM_packetPointer to access each
                                 // packet
SMM_packetPointer vfd_1_packet_01 = &SMM_packets[VFD_1_PACKET_1]; // Create a SMM_packetPointer to access each
                                 // packet
SMM_packetPointer vfd_1_packet_02 = &SMM_packets[VFD_1_PACKET_2]; // Create a SMM_packetPointer to access each
                                 // packet
SMM_packetPointer vfd_1_packet_03 = &SMM_packets[VFD_1_PACKET_3]; // Create a SMM_packetPointer to access each
                                 // packet
SMM_packetPointer vfd_1_packet_04 = &SMM_packets[VFD_1_PACKET_4]; // Create a SMM_packetPointer to access each
                                 // packet

void setup_mb_ip_vfd() {
  /// Se inician los valores de RED WiFi ///
  WiFi.mode(WIFI_STA);
  WiFi.config(local_IP, gateway, subnet, primaryDNS, secondaryDNS);
  WiFi.begin("Dedicado Wifi", "1008990aa");
  // Wait for connection
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
  }

  mb_ip_vfd.server();
  // Agrega registros lectura Modbus IP.
  mb_ip_vfd.addIreg(0, 0, 28); // (registro inicial, valor de registros, cantidad de registros)
}

void readData() {
  // should only be used to set/unset flags
  read_data = true;
}

void webSocketEvent(uint8_t num, WStype_t type, uint8_t *payload,
                    size_t length) {
  if (type == WStype_TEXT) {
    // processs any returned data
    //Serial.printf("payload [%u]: %s\n", num, payload);
  }
}

void setup_websocket() // Setup Servidor
{
  // define the routes in which the server is accessible
  server.on("/", []() { server.send_P(200, "text/html", webpage); });

  // initialize server and websockets
  server.begin();
  webSocket.begin();

  // initialize timer function
  timer.attach(/*rate in secs*/ 0.1, /*callback*/ readData);
  // handling incoming messages on the websocket
  webSocket.onEvent(webSocketEvent);
}


void loop_websockert()// Websocket
{
  webSocket.loop();
  server.handleClient();
  if (read_data) {

    String json = "{\"VFD_1_array_00\":";
    json += VFD_1_array_0[0];
    json += ",\"VFD_1_array_01\":";
    json += VFD_1_array_0[1];
    json += ",\"VFD_1_array_02\":";
    json += VFD_1_array_0[2];
    json += ",\"VFD_1_array_03\":";
    json += VFD_1_array_0[3];
    json += ",\"VFD_1_array_04\":";
    json += VFD_1_array_0[4];
    json += ",\"VFD_1_array_05\":";
    json += VFD_1_array_0[5];

    json += ",\"VFD_1_array_10\":";
    json += VFD_1_array_1[0];
    json += ",\"VFD_1_array_11\":";
    json += VFD_1_array_1[1];
    json += ",\"VFD_1_array_12\":";
    json += VFD_1_array_1[2];
    json += ",\"VFD_1_array_13\":";
    json += VFD_1_array_1[3];
    json += ",\"VFD_1_array_14\":";
    json += VFD_1_array_1[4];
    json += ",\"VFD_1_array_15\":";
    json += VFD_1_array_1[5];
    
    json += ",\"VFD_1_array_20\":";
    json += VFD_1_array_2[0];
    json += ",\"VFD_1_array_21\":";
    json += VFD_1_array_2[1];
    json += ",\"VFD_1_array_22\":";
    json += VFD_1_array_2[2];
    json += ",\"VFD_1_array_23\":";
    json += VFD_1_array_2[3];
    json += ",\"VFD_1_array_24\":";
    json += VFD_1_array_2[4];
    json += ",\"VFD_1_array_25\":";
    json += VFD_1_array_2[5];

    json += ",\"VFD_1_array_30\":";
    json += VFD_1_array_3[0];
    json += ",\"VFD_1_array_31\":";
    json += VFD_1_array_3[1];
    json += ",\"VFD_1_array_32\":";
    json += VFD_1_array_3[2];
    json += ",\"VFD_1_array_33\":";
    json += VFD_1_array_3[3];
    json += ",\"VFD_1_array_34\":";
    json += VFD_1_array_3[4];
    json += ",\"VFD_1_array_35\":";
    json += VFD_1_array_3[5];

    json += ",\"VFD_1_array_40\":";
    json += VFD_1_array_4[0];
    json += ",\"VFD_1_array_41\":";
    json += VFD_1_array_4[1];
    json += ",\"VFD_1_array_42\":";
    json += VFD_1_array_4[2];
    json += ",\"VFD_1_array_43\":";
    json += VFD_1_array_4[3];
    json += ",\"VFD_1_array_04\":";
    json += VFD_1_array_0[4];
    
    json += "}";
    //    Serial.println(json); // DEBUGGING
    webSocket.broadcastTXT(json.c_str(), json.length());
  }
}
void setup_rtu_vfd() // Setup Cliente Modbus Variadores.
{
  // Initialize communication settings etc...
  /// Master Modbus ///
  SMM_modbus_configure(SMM_baud, SMM_timeout, SMM_polling, SMM_retry_count,
                       SMM_TxEnablePin, SMM_packets, SMM_TOTAL_NO_OF_PACKETS);

  //////// Modbus Master Set /////////
  // read 3 registers starting at SMM_address 0
  vfd_1_packet_00->SMM_id = 3;                               // Slave ID.
  vfd_1_packet_00->SMM_function = SMM_READ_HOLDING_REGISTERS; // Function.
  vfd_1_packet_00->SMM_address = 3328;                        // Init Adds.
  vfd_1_packet_00->SMM_no_of_registers = 6;                   // Qty Read.
  vfd_1_packet_00->SMM_register_array = VFD_1_array_0;        // Name Array.

  vfd_1_packet_01->SMM_id = 3;                               // Slave ID.
  vfd_1_packet_01->SMM_function = SMM_READ_HOLDING_REGISTERS; // Function.
  vfd_1_packet_01->SMM_address = 3334;                        // Init Adds.
  vfd_1_packet_01->SMM_no_of_registers = 6;                   // Qty Read.
  vfd_1_packet_01->SMM_register_array = VFD_1_array_1;        // Name Array.

  vfd_1_packet_02->SMM_id = 3;                               // Slave ID.
  vfd_1_packet_02->SMM_function = SMM_READ_HOLDING_REGISTERS; // Function.
  vfd_1_packet_02->SMM_address = 3340;                        // Init Adds.
  vfd_1_packet_02->SMM_no_of_registers = 6;                   // Qty Read.
  vfd_1_packet_02->SMM_register_array = VFD_1_array_2;        // Name Array.

  vfd_1_packet_03->SMM_id = 3;                               // Slave ID.
  vfd_1_packet_03->SMM_function = SMM_READ_HOLDING_REGISTERS; // Function.
  vfd_1_packet_03->SMM_address = 3346;                        // Init Adds.
  vfd_1_packet_03->SMM_no_of_registers = 6;                   // Qty Read.
  vfd_1_packet_03->SMM_register_array = VFD_1_array_3;        // Name Array.

  vfd_1_packet_04->SMM_id = 3;                               // Slave ID.
  vfd_1_packet_04->SMM_function = SMM_READ_HOLDING_REGISTERS; // Function.
  vfd_1_packet_04->SMM_address = 3352;                        // Init Adds.
  vfd_1_packet_04->SMM_no_of_registers = 4;                   // Qty Read.
  vfd_1_packet_04->SMM_register_array = VFD_1_array_4;        // Name Array.

  

}

void loop_rtu_vfd_1() // Loop Comunicación Variador 1
{
  SMM_modbus_update(SMM_packets); // Update Master array.

 
  VFD_1_array_00 = VFD_1_array_0[0];
  VFD_1_array_01 = VFD_1_array_0[1];
  VFD_1_array_02 = VFD_1_array_0[2];
  VFD_1_array_03 = VFD_1_array_0[3];
  VFD_1_array_04 = VFD_1_array_0[4];
  VFD_1_array_05 = VFD_1_array_0[5];

  

  VFD_1_array_10 = VFD_1_array_1[0];
  VFD_1_array_11 = VFD_1_array_1[1];
  VFD_1_array_12 = VFD_1_array_1[2];
  VFD_1_array_13 = VFD_1_array_1[3];
  VFD_1_array_14 = VFD_1_array_1[4];
  VFD_1_array_15 = VFD_1_array_1[5];

  

  VFD_1_array_20 = VFD_1_array_2[0];
  VFD_1_array_21 = VFD_1_array_2[1];
  VFD_1_array_22 = VFD_1_array_2[2];
  VFD_1_array_23 = VFD_1_array_2[3];
  VFD_1_array_24 = VFD_1_array_2[4];
  VFD_1_array_25 = VFD_1_array_2[5];

  

  VFD_1_array_30 = VFD_1_array_3[0];
  VFD_1_array_31 = VFD_1_array_3[1];
  VFD_1_array_32 = VFD_1_array_3[2];
  VFD_1_array_33 = VFD_1_array_3[3];
  VFD_1_array_34 = VFD_1_array_3[4];
  VFD_1_array_35 = VFD_1_array_3[5];

  

  VFD_1_array_40 = VFD_1_array_4[0];
  VFD_1_array_41 = VFD_1_array_4[1];
  VFD_1_array_42 = VFD_1_array_4[2];
  VFD_1_array_43 = VFD_1_array_4[3];
  
}

void loop_tcp_vfd()
{
  SMM_modbus_update(SMM_packets); // Update Master array.

  mb_ip_vfd.Ireg(0, VFD_1_array_0[0]);
  mb_ip_vfd.Ireg(1, VFD_1_array_0[1]);
  mb_ip_vfd.Ireg(2, VFD_1_array_0[2]);
  mb_ip_vfd.Ireg(3, VFD_1_array_0[3]);
  mb_ip_vfd.Ireg(4, VFD_1_array_0[4]);
  mb_ip_vfd.Ireg(5, VFD_1_array_0[5]);
  

  mb_ip_vfd.Ireg(6, VFD_1_array_1[0]);
  mb_ip_vfd.Ireg(7, VFD_1_array_1[1]);
  mb_ip_vfd.Ireg(8, VFD_1_array_1[2]);
  mb_ip_vfd.Ireg(9, VFD_1_array_1[3]);
  mb_ip_vfd.Ireg(10, VFD_1_array_1[4]);
  mb_ip_vfd.Ireg(11, VFD_1_array_1[5]);
  //mb_ip_vfd.task();

  mb_ip_vfd.Ireg(12, VFD_1_array_2[0]);
  mb_ip_vfd.Ireg(13, VFD_1_array_2[1]);
  mb_ip_vfd.Ireg(14, VFD_1_array_2[2]);
  mb_ip_vfd.Ireg(15, VFD_1_array_2[3]);
  mb_ip_vfd.Ireg(16, VFD_1_array_2[4]);
  mb_ip_vfd.Ireg(17, VFD_1_array_2[5]);
  //mb_ip_vfd.task();

  mb_ip_vfd.Ireg(18, VFD_1_array_3[0]);
  mb_ip_vfd.Ireg(19, VFD_1_array_3[1]);
  mb_ip_vfd.Ireg(20, VFD_1_array_3[2]);
  mb_ip_vfd.Ireg(21, VFD_1_array_3[3]);
  mb_ip_vfd.Ireg(22, VFD_1_array_3[4]);
  mb_ip_vfd.Ireg(23, VFD_1_array_3[5]);
  //mb_ip_vfd.task();

  mb_ip_vfd.Ireg(24, VFD_1_array_4[0]);
  mb_ip_vfd.Ireg(25, VFD_1_array_4[1]);
  mb_ip_vfd.Ireg(26, VFD_1_array_4[2]);
  mb_ip_vfd.Ireg(27, VFD_1_array_4[3]);
  mb_ip_vfd.task();
}


void setup() // Configuración inicial
{
  setup_mb_ip_vfd();
  
  setup_rtu_vfd();
  setup_websocket();
}

void loop() // Loop Principal
{
  //loop_rtu_vfd_1();
  loop_tcp_vfd();
loop_websockert();
  delay(1);
}`

and here the code of my h.

`#pragma once
#ifndef VFD_MODBUSIP_WEBSOCKETH
#define VFD_MODBUSIP_WEBSOCKETH
#include <Arduino.h>

// Configuración de parametros Cliente Modbus.
///////// Modbus master /////////
//////////////////// Port information Serial 2 ///////////////////
const long SMM_baud = 38400;          // Communication Velocity.
const unsigned int SMM_timeout = 500; // Time of retry.
const unsigned int SMM_polling = 300; // the scan rate.
const unsigned char SMM_retry_count =
    255; // the set retry count then communication is stopped.
const unsigned char SMM_TxEnablePin =
    0; // used to toggle the receive/transmit pin on the driver.

// Debido a las limitaciones del VFD solo se puede acceder a 6 registros por llamada.
// los valores de los registros se guardan el los array.
unsigned int VFD_1_array_0[6]; // Se almacenan los datos del Paquette 0.
unsigned int VFD_1_array_1[6]; // Se almacenan los datos del Paquette 1.
unsigned int VFD_1_array_2[6]; // Se almacenan los datos del Paquette 2.
unsigned int VFD_1_array_3[6]; // Se almacenan los datos del Paquette 3.
unsigned int VFD_1_array_4[4]; // Se almacenan los datos del Paquette 4.

int VFD_1_array_00 = 3328;
int VFD_1_array_01 = 3329;
int VFD_1_array_02 = 3330;
int VFD_1_array_03 = 3331;
int VFD_1_array_04 = 3332;
int VFD_1_array_05 = 3333;

int VFD_1_array_10 = 3334;
int VFD_1_array_11 = 3335;
int VFD_1_array_12 = 3336;
int VFD_1_array_13 = 3337;
int VFD_1_array_14 = 3338;
int VFD_1_array_15 = 3339;

int VFD_1_array_20 = 3340;
int VFD_1_array_21 = 3341;
int VFD_1_array_22 = 3342;
int VFD_1_array_23 = 3343;
int VFD_1_array_24 = 3344;
int VFD_1_array_25 = 3345;

int VFD_1_array_30 = 3346;
int VFD_1_array_31 = 3347;
int VFD_1_array_32 = 3348;
int VFD_1_array_33 = 3349;
int VFD_1_array_34 = 3350;
int VFD_1_array_35 = 3351;

int VFD_1_array_40 = 3352;
int VFD_1_array_41 = 3353;
int VFD_1_array_42 = 3354;
int VFD_1_array_43 = 3355;

// This is the easiest way to create new SMM_packets
// Add as many as you want. SMM_TOTAL_NO_OF_PACKETS
// is automatically updated.
enum master {
  VFD_1_PACKET_0,
  VFD_1_PACKET_1,
  VFD_1_PACKET_2,
  VFD_1_PACKET_3,
  VFD_1_PACKET_4,
  SMM_TOTAL_NO_OF_PACKETS
}; // End enum master.

#endif`

**Comment by fbi1671** [comment]
I used the awesome library for my virtual modbus sms gateway, tested up to 247 server id on a single esp32.
I use it for my remote rtu that send data over gsm.  so the esp32 act as a bridge to the client.  each remote rtu is assigned a modbus id.  next week, i will install some 20 more remote rtu.  we'll see how the bridge react.

**Comment by emelianov** [comment]
9b859db
