### ISSUE TITLE
Help with Modbus RTU - TCP bridge

### ISSUE THREAD

**Issue by goossensbas** [emelianov/modbus-esp8266#166]
Hello,

I have been playing around with the library to make a modbus gateway for my ventilation unit.
I managed to setup the RTU master and the TCP slave successfully, but it seems that the data between RTU and TCP are not linked.

What am i doing wrong?

`void setup()
{ 
  Serial.begin(9600); // for logging purpose only
  while (!Serial) {}
  Serial.println("__ Serial1 OK __");
  Serial2.begin(BAUDRATE, SERIAL_8N1, RXPIN, TXPIN);
  Serial2.println("Serial2 OK");
  setup_wifi();

  mb1.begin(&Serial2, 4);
  //mb1.begin(&Serial2, 17);  // Specify RE_DE control pin
  mb1.master();
  mb2.server();
    for (int i = 0; i < MAX_PARAMS; i++){
      mb2.addHreg(50);
  }
}

void loop()
{
  ArduinoOTA.handle();
  if(!mb1.slave())
//{
//  for (int i = 0; i < MAX_PARAMS; i++){
//    mb1.readHreg(10, MAX_PARAMS, data, MAX_PARAMS, cbWrite);
//  }
//  }  
  yield();
  mb1.pullHreg(10, 50, 1);
  yield();
  mb1.task();
  yield();
  mb2.task();
  yield();
  delay(50);
}`

Would it also be possible to forward the FC commands from the TCP slave to the RTU master directly?

thanks in advance for the help!

**Comment by emelianov** [comment]
Hi,
Direct forward is possible but not merged to master branch yet. Take a look [TrueBridge example](https://github.com/emelianov/modbus-esp8266/tree/truebridge/examples/Bridge)

As for your existing code it's not clear about what Hregs you need to read/write, bu may be it's used to be something like 
```c
void setup()
{
//...
  mb2.addHreg(0, 0, MAX_PARAMS); // Add MAX_PARAMS local Hregs starting from Hreg 0
}
}
void loop()
{
ArduinoOTA.handle();
if(!mb1.slave()) {
  mb1.pullHreg(10, 50, 1); // Read [one] Hreg 50 from slave 10 and save it to local Hreg 1
}
mb1.task();
mb2.task();
yield();
delay(50);
}
```
