### ISSUE TITLE
Two modbus requests together -> CRC Fail 

### ISSUE THREAD

**Issue by gonzabrusco** [emelianov/modbus-esp8266#169]
Hello!

I'm having a problem and I was wondering if you could help me out. The problem I'm having with your library is that the task() function in ModbusRTU.cpp is not checking if the buffer has two frames together because the code hanged out in another place of the program (unrelated to modbus). 

Now the code works waiting for the white space to know when the frame is over. But if task() entered with a second request arriving, it will wait for the white space of the second request. But then it will calculate the CRC for all de buffer in the Serial Port (_port->read()). The problem is that this CRC will fail and the modbus slave wont even answer the second request that just received.

The task() routing should be modified so that it knows the expected length of the request based on the type of request. What do you think? This way the task() can ignore the first request in the buffer and just process the recently arrived.

**Comment by emelianov** [comment]
Hello,
It looks like abnormal processing scenario. Typically no response timeout value is much longer than loop() time. If not I consider it should be resolved on application side. So I prefer do not overengineering task() code.
In case of ESP32 Modbus processing may be implemented as dedicated task. Related example is [ESP32-Concurent](https://github.com/emelianov/modbus-esp8266/tree/master/examples/RTU/ESP32-Concurent)
