### ISSUE TITLE
Dash in filenames not allowed in Arduino for Linux 

### ISSUE THREAD

**Issue by wvsbsp** [emelianov/modbus-esp8266#176]
**Describe the bug**

After installing the library, Arduino starts with error-messages "non ASCII characters in filenames".
In the Linux Version of Arduino no dashes are allowed in filenames (and so also in the containing folder-names)
Most of your examples contain dashes in the filename.

**Environment**
- Version of Arduino IDE being used.
Arduino 1.8.13, Linux Mint 20.2

**To Reproduce**
install Linux...

**Expected behavior**
regular start of arduino.

**Additional Information**
i could just rename the files, but with the next update of the library, the problem will reappear. => Please rename your examples.

**Comment by emelianov** [comment]
7a213b3
