### ISSUE TITLE
MODBUSIP_UNIT is Hardcoded

### ISSUE THREAD

**Issue by Msafiri70** [emelianov/modbus-esp8266#18]
Hello,
the MODBUSIP_UNIT is hardcoded to 255, is it possible to change the code that at a read (Hreg, Ireg) the Unit is passed to the function?
I have a Victron Solarsystem where a single IP has many Units, so hardcoded is a problem as i need to read from many different Units to collect my data.
Regards,
Sander van Noort

**Comment by emelianov** [comment]
Hello Sander,

All functions related to slave querying already has such parameter. For example for readHreg/Ireg
```c
uint16_t readHreg(IPAddress ip, uint16_t offset, uint16_t* value, uint16_t numregs = 1, cbTransaction cb = nullptr, uint8_t unit = MODBUSIP_UNIT);
uint16_t readIreg(IPAddress ip, uint16_t offset, uint16_t* value, uint16_t numregs = 1, cbTransaction cb = nullptr, uint8_t unit = MODBUSIP_UNIT);
```
So you need just write all parameters (last parameter is Modbus unit):
```c
uint16_t dst;
readHreg(IPAddress(192, 168, 1, 100), 20, &dst, 1, nullptr, 1);
```
