### ISSUE TITLE
Library issue 

### ISSUE THREAD

**Issue by simogaspa84** [emelianov/modbus-esp8266#181]
Hi.. I have tried to use the library cleaning the code and building all from the beginning.. Have you aver faced this issue ?

![image](https://user-images.githubusercontent.com/12874425/152372267-15ba03ca-6553-4597-9db2-9c039123a407.png)

**Comment by emelianov** [comment]
It looks like PlatformIO build issue. I'll try to check it.

**Comment by emelianov** [comment]
Local Platformio project configuration issue.
