### ISSUE TITLE
[Help wanted] read (multiple) modbus devices - sensors

### ISSUE THREAD

**Issue by RosiersRobin** [emelianov/modbus-esp8266#192]
Hi,

I'm fairly new to modbus and it's capabilities. Now I have a program called "QmodMaster" and I'm able to read the modbus device via my computer. When I do the exact same thing on my ESP32 with this package, nothing hapens...

this is the code:

```cpp
#include <ModbusRTU.h>
#include <SoftwareSerial.h>

SoftwareSerial modBusSerial;

ModbusRTU modbus;

#define startReg 100
#define endReg 123
uint16_t res[endReg - startReg + 1];

// Callback to monitor errors in the modbus
bool cb(Modbus::ResultCode event, uint16_t transactionId, void* data) {
    if (event != Modbus::EX_SUCCESS) {
        Serial.print("Request result: 0x");
        Serial.print(event, HEX);
    }
    return true;
}

void setup() {

    Serial.begin(115200); // Default serial port (Hardware serial)

    modBusSerial.begin(9600, SWSERIAL_8E1, MB_RX, MB_TX); // modbus configuration SWSERIAL_8E1 = 8 bits data, even parity and 1 stop-bit
    modbus.begin(&modBusSerial);
    modbus.master();
    Serial.println("starting modbus...");

    while (true) {
        Serial.println(modBusSerial.read());

        res[endReg - startReg] = 0;  // string terminator to allow to use res as char*

        if (!modbus.slave()) {
            modbus.readIreg(16, startReg, res, endReg - startReg, cb);
        }
        modbus.task();
        Serial.print("result: ");
        Serial.println((char*) res);
        delay(1000); // every second
    }
}

```

this is the response I get;

![image](https://i.imgur.com/w6GHYnX.png)

This is what is setup in the QmodMaster;

![QmodMaster](https://i.imgur.com/3smHvjz.png)

**I am aware that the slave address in the code is 17 and in the QModMaster is 7, the address in the code is the address of that device connected..**

Any idea what I'm doing wrong here? I just want to get the values and then be able to use them.

**Comment by emelianov** [comment]
1. For ESP32 it's much better to use HardwareSerial Serial2

2. Note `while (mb.slave())` loop. We should execute `mb.task()` until got response from slave.
That's because internally:
- `readIreg()` sends just request and exits
- `task()` processes response and fills `res` with result. But if no response arrived yet `tusk()` just exits. So we need to call it while `slave()` returning `true` (that means transaction in act). 
```c
while (true) {
        Serial.println(modBusSerial.read());

        res[endReg - startReg] = 0;  // string terminator to allow to use res as char*

        if (!modbus.slave()) {
            modbus.readIreg(16, startReg, res, endReg - startReg, cb);
        }
        while (mb.slave())
          modbus.task();
        Serial.print("result: ");
        Serial.println((char*) res);
        delay(1000); // every second
    }
```

**Comment by RosiersRobin** [comment]
@emelianov thanks for the quick response!

I know that the UARTS are a better use for modbus, however, those are already used by faster devices, so I'm kinda bound to using software serial...

Anyow, I have updated my code according to your input and changed it to the following;

```
while (true) {
        if (!mb.slave()) {
            // slave_ID, Start registers, data_placeholder, end registers, callback function
            mb.readIreg(16, startReg, res, endReg - startReg, cb);
        }
        while (mb.slave()) {
            mb.task(); // listen to the thing.
            vTaskDelay(1);
        }
        Serial.print("result: ");
        Serial.println((char*) res);
        delay(1000); // every second
    }
```

Now I still get the same error, I did redefine the start and endreg;

```
#define startReg 100
#define endReg 110
uint16_t res[endReg - startReg + 1];
```

I have Input registers from [100 ... 110]

Output:

```
09:40:00.233 -> Request result: 0xE4result: 
09:40:02.241 -> Request result: 0xE4result: 
09:40:04.246 -> Request result: 0xE4result: 
09:40:06.256 -> Request result: 0xE4result: 
09:40:08.256 -> Request result: 0xE4result: 
```

So the Callback (cb) function in the `mb.readIreg` reports the "request result: 0xE4" and then the "result:" is empty.

**Comment by emelianov** [comment]
0xE4 error means request timeout. That is no response received from slave within 1 second.
As code looks correct there are two possible reasons:
- wiring or transceiver issues
- SoftwareSerial issues. Probably you may try to use different versions of SoftwareSerial library.
Also ultimate solution to get the idea of the issue reason is to monitor outgoing traffic from ESP32 on SoftwareSerial or/and RS-485.

**Comment by RosiersRobin** [comment]
@emelianov I bet it will be a transceiver issue, how can I use that package for half-duplex tranceivers? I don't seem to pass along a pin or am I missing something?

**Comment by emelianov** [comment]
From the library side
```c
modbus.begin(&modBusSerial, RE_DE_PIN);
```
From the transceiver side, wiring depends on hardware.

**Comment by RosiersRobin** [comment]
Is there an option to 'invert' the RE_DE_PIN mode? 

I still seem to get 

```
Request failed with result: 0xE4
14:39:17.387 -> result: 
14:39:18.371 -> -1

```

As output...

I know that the connected senors are not the issue.
It can be the hardware, or software, but I don't know how I could check the hardware on this...

**Comment by emelianov** [comment]
> Is there an option to 'invert' the RE_DE_PIN mode?

Sure:
```c
modbus.begin(&modBusSerial, RE_DE_PIN, false);
```

> I know that the connected senors are not the issue. It can be the hardware, or software, but I don't know how I could check the hardware on this...

Try to connect ESP to PC with Modbus Slave emulator running. You can examine the data flow from/to ESP.

**Comment by RosiersRobin** [comment]
So it was a hardware problem, not a software problem. the given code worked like a charm!

Keep up the awesome work! and thanks alot!!!
