### ISSUE TITLE
Won't compile sending multiple registers using writeHreg

### ISSUE THREAD

**Issue by Uksa007** [emelianov/modbus-esp8266#202]
Sending one register works ok, eg mb.writeHreg(0xF7, 0x056E, 0x0003, cbWrite);

I get the following error compiling on ESP8266 when trying to send multiple registers:
no matching function for call to 'ModbusRTU::writeHreg(int, int, uint16_t (*)[5], int, bool (&)(Modbus::ResultCode, uint16_t, void*))'

A simple mb.writeHreg(0xF7, 0x056E, 0x0003, 0x1388, 2 ,cbWrite); fails to compile.
Am i doing something wrong or is it a bug?

#define SLAVE_ID 0xF7
#define FIRST_REG 0x056E
#define NUM_REG 2
uint16_t regs[NUM_REG] = {0x0003, 0x1388};

bool cbWrite(Modbus::ResultCode event, uint16_t transactionId, void* data) {
  Serial.printf_P("Request result: 0x%02X, Mem: %d\n", event, ESP.getFreeHeap());
  return true;
}

void loop() {
  if (!mb.slave()) {
    mb.writeHreg(SLAVE_ID, FIRST_REG, &regs, NUM_REG, cbWrite);
  }
  mb.task();
}

**Comment by emelianov** [comment]
```c
mb.writeHreg(SLAVE_ID, FIRST_REG, (uint16_t*)&regs, NUM_REG, cbWrite);
```
