### ISSUE TITLE
Print all the packets received

### ISSUE THREAD

**Issue by simogaspa84** [emelianov/modbus-esp8266#207]
Hi Emelianov and thanks again for your lib.. 
Just a question I have configured my esp32 as a slave in the modbus network.
How can I easily print to the terminal all the packets that I am receiving from the master?

Thanks a lot

**Comment by emelianov** [comment]
You may uncomment

```c
#define MODBUSRTU_DEBUG
```

in `ModbusSettings.h`. If that's not enough you may add additional debug output to following methods in `ModbusRTU.h`:

```c
uint16_t ModbusRTUTemplate::send(uint8_t slaveId, TAddress startreg, cbTransaction cb, uint8_t unit, uint8_t* data, bool waitResponse);
void ModbusRTUTemplate::task();
```

**Comment by simogaspa84** [comment]
Thanks Emelianov..
