### ISSUE TITLE
Modbus TCP communication ENC28J60 and ESP32

### ISSUE THREAD

**Issue by elektroboard** [emelianov/modbus-esp8266#211]
Hello. I want to communicate ModbusTCP with ESP32 and ENC28j60 ethernet module. However, I couldn't. What sample code should I use?

**Comment by emelianov** [comment]
Hi.
[ModbusEthernet](https://github.com/emelianov/modbus-esp8266/tree/master/examples/TCP-Ethernet) should work for ENC28J60 too.

**Comment by elektroboard** [comment]
Hi.
I try to your "server.ino" file. . But there is a error and dont connect. An error code appeared: Trying to connect to remote TCP server...
Socket error #10061 . What'is problem?

**Comment by emelianov** [comment]
It's [reported](https://github.com/emelianov/modbus-esp8266/issues/101#issuecomment-752189158) that the library is working with enc28j60 using [UIPEthernet library](https://github.com/UIPEthernet/UIPEthernet).
So yon need to modify example code to use UIPEthernet.h instead Ethernet.h.

**Comment by elektroboard** [comment]
Thank. I will try.

**Comment by JAlvares20** [comment]
Hello. Next week I'll do the same project with the same components. I just want to know if what you did worked?

**Comment by emelianov** [comment]
No any news since than.
