### ISSUE TITLE
getting response timeout on the client side from the esp32 TCP server!

### ISSUE THREAD

**Issue by MohsenELV** [emelianov/modbus-esp8266#213]
Hi Emelianov.

i am using esp32 as TCP modbus server(wifi)!
i am gathering information from a device and update them into bool arrays!
then i just move the arrays values into discrete inputs i added on the server!
everything was working just fine!

but if my data gathering process takes time (1s-2s) inside the Loop() i start getting response timeouts (20% of POLLS) on the client side!
i tried to call mb.task() in different parts of my code but didn't work out! i also used different delay values after the task but same result!

is it enough to call the mb.task just once inside the loop or do i have to repeat it regularly? can i use timer interrupts to call mb.task() regularly? please advise your suggested time interval to call the mb.task().   
can we use the second core to handle the mb.task()?

thanks for your help in advance.

**Comment by emelianov** [comment]
For server maximum delay between .task() calls depends on client timeout settings.
In case of ESP32 it's suggested to run two separate tasks:
- one for modbus server
- another for data gathering process
For sure you need to use queue of another interprocess communication or data synchronization technique to fill modbus registers with gathered values.
