### ISSUE TITLE
Question: can it work with modbus using RS232

### ISSUE THREAD

**Issue by rmallah** [emelianov/modbus-esp8266#224]
Hi , 

Will this module work with a transceiver like MAX3232
which converts RS232 levels to TTL levels.

The protocol is MODBUS but communications is via RS232

Regds
Rajesh.

**Comment by emelianov** [comment]
The library operates with Serial and doesn't care about physical layer. So it should work out of box.

**Comment by rmallah** [comment]
Thanks for the response. I will post the results either way. I am waiting for 
my RS232 To TTL Serial Interface Module to arrive.
