### ISSUE TITLE
Problem during Reading Multiple Slave Data

### ISSUE THREAD

**Issue by ashish8284** [emelianov/modbus-esp8266#228]
Hi,
First of all thanks a lot for doing great job.
What i have did yet :- 
I have read data from Modbus slaves(energy meter) using esp8266 chip.   I have used Modbus master example and edit it for Schneider make EM6400 meter data reading.

I have read data from multiple slaves by Changing Slave I'd after reading each slave data and re set I'd to starting in reaching last slave.

I tried 10 slaves which works fine for me.

Problem.

If any one slave is not responding(power off) I still get data of previous slave data from buffer.

I.e.

Slave01.  Data recieved & Stored in variable 

Slave02.  Data received & Stored in variable

Slave03.  Not responding
But still i get data of slave02 from buffer.

**Comment by emelianov** [comment]
Simplest way is to fill data with some 'impossible' value before reading. So if value 'impossible' value persists that mean reading was unsuccessful.
More complex way is to control operation result by setting transaction callback.
