### ISSUE TITLE
Multiple client connection on TCP server

### ISSUE THREAD

**Issue by DavideTurra** [emelianov/modbus-esp8266#231]
thank you for this useful library. 

Is it possible to have multiple client connection for a TCP server in some way?

thanks in advance

**Comment by emelianov** [comment]
Sure. Number of simultaneous connections for client or server is limited by Arduino's tcp stack implementation.
The only limitation that the library is support only single client (outgoing) connection per server IP.

**Comment by DavideTurra** [comment]
ok thank you for the answer, may be I made some mistake somewere in my code. All the best to you

**Comment by papercodeIN** [comment]
> Sure. Number of simultaneous connections for client or server is limited by Arduino's tcp stack implementation. The only limitation that the library is support only single client (outgoing) connection per server IP.

Means from different system with different IP address I can connect to Same Modbus TCP Server. So, this is how it will support multiple connection correct ?
