### ISSUE TITLE
Server Client Configration 

### ISSUE THREAD

**Issue by tarekanwer** [emelianov/modbus-esp8266#234]
Hi there, 

Hope you are doing well. I am tring to have a modbus communication using 2 arduino mega with their ethernet shields. I am quite stucked in the process. Hope you can help me. really appricate you time. 

Regards,

**Comment by emelianov** [comment]
[Ethernet client and server examples](https://github.com/emelianov/modbus-esp8266/tree/master/examples/TCP-Ethernet) should help you.
