### ISSUE TITLE
Can read only 14 Input Register

### ISSUE THREAD

**Issue by syah125** [emelianov/modbus-esp8266#241]
Hi. Is there any way to read more than 14 Input Register? I need to read more than 100 register. Here is my code.
`
#ifdef ESP8266
 #include <ESP8266WiFi.h>
#else
 #include <WiFi.h>
#endif
#include <ModbusIP_ESP8266.h>
#include <InfluxDbClient.h>

#define INFLUXDB_URL "INFLUXDB_URL"
// InfluxDB database name
#define INFLUXDB_DB_NAME "DATABASE"

InfluxDBClient client(INFLUXDB_URL, INFLUXDB_DB_NAME);

const int ActivePower = 3004;   
const int DCOut = 3007; 
const int TotalEnergy = 3009;// Modbus Hreg Offset
IPAddress remote(192, 168, 0, 22);  // Address of Modbus Slave device
const int LOOP_COUNT = 10;

ModbusIP mb;  //ModbusIP object

Point sensor("inverter1");

void setup() {
  Serial.begin(115200);
 
  WiFi.begin("SSID", "PASSWORD");
  
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected");  
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());

  mb.client();

   if (client.validateConnection()) {
    Serial.print("Connected to InfluxDB: ");
    Serial.println(client.getServerUrl());
  } else {
    Serial.print("InfluxDB connection failed: ");
    Serial.println(client.getLastErrorMessage());
  }

}

uint16_t res = 0;
uint16_t res1 = 0;
uint16_t res2 = 0;
uint16_t res3 = 0;
uint16_t res4 = 0;
uint16_t res5 = 0;
uint16_t res6 = 0;
uint16_t res7 = 0;
uint16_t res8 = 0;
uint16_t res9 = 0;
uint16_t res10 = 0;
uint16_t res11 = 0;
uint16_t res12 = 0;
uint16_t res13 = 0;
uint16_t res14 = 0;
uint16_t res15 = 0;
uint16_t res16 = 0;
uint16_t res17 = 0;
uint16_t res18 = 0;
uint16_t res19 = 0;
uint16_t res20 = 0;
uint16_t res21 = 0;
uint16_t res22 = 0;
uint16_t res23 = 0;
uint16_t res24 = 0;
uint16_t res25 = 0;
uint16_t res26 = 0;
uint16_t res27 = 0;
uint16_t res28 = 0;
uint16_t res29 = 0;
uint16_t res30 = 0;

void loop() {
  if (mb.isConnected(remote)) {   // Check if connection to Modbus Slave is established
    uint16_t trans = mb.readIreg(remote, 3005, &res, 1, nullptr, 1); 
     mb.readIreg(remote, 3006, &res1, 1, nullptr, 1);
     mb.readIreg(remote, 3007, &res2, 1, nullptr, 1);
     mb.readIreg(remote, 3008, &res3, 1, nullptr, 1);
     mb.readIreg(remote, 3009, &res4, 1, nullptr, 1);
     mb.readIreg(remote, 3010, &res5, 1, nullptr, 1);
     mb.readIreg(remote, 3011, &res6, 1, nullptr, 1);
     mb.readIreg(remote, 3012, &res7, 1, nullptr, 1);
     mb.readIreg(remote, 3013, &res8, 1, nullptr, 1);
     mb.readIreg(remote, 3014, &res9, 1, nullptr, 1);
     mb.readIreg(remote, 3015, &res10, 1, nullptr, 1);
     mb.readIreg(remote, 3016, &res11, 1, nullptr, 1);
     mb.readIreg(remote, 3017, &res12, 1, nullptr, 1);
     mb.readIreg(remote, 3018, &res13, 1, nullptr, 1);
     mb.readIreg(remote, 3019, &res14, 1, nullptr, 1);
     mb.readIreg(remote, 3020, &res15, 1, nullptr, 1);
     mb.readIreg(remote, 3022, &res16, 1, nullptr, 1);
     mb.readIreg(remote, 3023, &res17, 1, nullptr, 1);
     mb.readIreg(remote, 3024, &res18, 1, nullptr, 1);
     mb.readIreg(remote, 3025, &res19, 1, nullptr, 1);
     mb.readIreg(remote, 3026, &res20, 1, nullptr, 1);
     mb.readIreg(remote, 3027, &res21, 1, nullptr, 1);
     mb.readIreg(remote, 3028, &res22, 1, nullptr, 1);
     mb.readIreg(remote, 3029, &res23, 1, nullptr, 1);
     
     
     
     
     
     
     //// Initiate Read Hreg from Modbus Server
    while(mb.isTransaction(trans)) {  // Check if transaction is active
  mb.task();
      delay(10);
    }
      sensor.addField("activepower", res+res1);
      sensor.addField("dcoutput", res2+res3);
      sensor.addField("totalenergy", res4+res5);
      sensor.addField("energy_this_month", res6+res7);
      sensor.addField("energy_last_month", res8+res9);
      sensor.addField("energy_today", res10);
      sensor.addField("energy_yesterday", res11);
      sensor.addField("energy_this_year", res12+res13);
      sensor.addField("energy_last_year", res14+res15);
      sensor.addField("dcvolt1", res16);
      sensor.addField("dccur1", res17);
      sensor.addField("dcvolt2", res18);
      sensor.addField("dccur2", res19);
      sensor.addField("dcvolt3", res20);
      sensor.addField("dccur3", res21);
      sensor.addField("dcvolt4", res22);
      sensor.addField("dccur4", res23);

      if (!client.writePoint(sensor)) {
    Serial.print("InfluxDB write failed: ");
    Serial.println(client.getLastErrorMessage());
  }

Serial.println("Writing Successfully");
  } else {
    mb.connect(remote);           // Try to connect if no connection
  }
  delay(3000);
}
`

**Comment by hall1235** [comment]
uint16_t readIreg(IPAddress ip, uint16_t offset, uint16_t* value, uint16_t numregs = 1, cbTransaction cb = nullptr, uint8_t uint = MODBUSIP_UNIT);

try this
