### ISSUE TITLE
Write Single Holding Register on Modbus functio code 06

### ISSUE THREAD

**Issue by simogaspa84** [emelianov/modbus-esp8266#246]
Hi @emelianov 

Can you provide an example code about how to call a single holding register write function? 

Example

0B 06 0004 ABCD 7604

0B: The Slave Address (0B hex = address 11)
06: The Function Code 6 (Write Single Holding Register)
0004: The Data Address of the register (0004 hex = 4, + 40001 offset = register #40005).
ABCD: The value to write.
7604: The CRC (Cyclic Redundancy Check) for error checking.

Thanks a lot

**Comment by emelianov** [comment]
#247
