### ISSUE TITLE
Maximum register is too small

### ISSUE THREAD

**Issue by OpenLogical** [emelianov/modbus-esp8266#25]
#define MB_MAX_REGS     32

Is it possible to default the library to a higher value, say 512?

Also is there a way I can update the  Holding/Input register value direct via pointer instead of calling Ireg/Hreg ?

Any help is appreciated!

Thanks for your wonderful work!

**Comment by emelianov** [comment]
You can change MB_MAX_REGS defenition or even remove it (to no limit at all). In fact count of registers is limited by available RAM. Memory allocated dynamicly at register addition.

You can write registers directly with slight Modbus source modification. No such functionalyty planned to be inluded in master branch as it'll break Callback functionality.
