### ISSUE TITLE
ESP32-Concurent.ino example of how to implement a write in a register?

### ISSUE THREAD

**Issue by franciscogimeno2000** [emelianov/modbus-esp8266#252]
Hello friends, in the example "ESP32-Concurrent.ino" it describes how to read I have searched but I can't find an example of how to implement a write in a register in concurrent mode. Do you know where I can find something?

Greetings and thank you. Great job Emilianov and group.
Fran

**Comment by emelianov** [comment]
Write is pretty much the same as read. Just replace `readHreg()` with `writeHreg()`.
