### ISSUE TITLE
One Master multiple slaves

### ISSUE THREAD

**Issue by Ricardosgeral** [emelianov/modbus-esp8266#267]
Hi, 
From documentation, I don't understand if the library can be used with multiple slaves.
Just to be clear in my mind, can I make a for loop in master to call each slave consecutively? Will that overload the line bus? should i wait some milliseconds between calls?

**task()** method in _slave_ will only reply if the _master_ asks something, right?

last question:
what  **yield()** in end of the loop() does?

Sorry for newbie questions

**Comment by Merdock1** [comment]
[Function yield](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/freertos.html#c.taskYIELD)

**Comment by emelianov** [comment]
>  can I make a for loop in master to call each slave consecutively? 
> Will that overload the line bus? should i wait some milliseconds between calls?

If you are using RTU you have to wait response for the request before sending next one. This is actual regardless you are sending request to the same slave or to different slaves.
