### ISSUE TITLE
Bug: Slave answers with malformed packet

### ISSUE THREAD

**Issue by qdlmcfresh** [emelianov/modbus-esp8266#268]
Lets say the Slave receives a packet like this, with a faulty length field
```python
packet = (
    #Request - modbus_read_coil
    #Block - modbus_head
    b'\x01\x00'  # Word - transId
    b'\x00\x00'  # Word - protoId
    + b'\x00' * 2 + #  Word -length
    b'\xff'  # Byte - unit Identifier
    #Block - pdu
    b'\x01'  # Byte - funcCode read coil memory
    b'\x00\x01'  # Word - start_address
    b'\x00\x00'  # Word - quantity
)
```
After correcty registering that the request is faulty, the slave will response with a malformed modbus packet with only 
8 bytes length, since:
`_len` first gets set to 2 here: 
https://github.com/emelianov/modbus-esp8266/blob/299666307a052df52f757f3131e292c2513bb57f/src/Modbus.cpp#L454-L457
then substracted by 1 here:
https://github.com/emelianov/modbus-esp8266/blob/299666307a052df52f757f3131e292c2513bb57f/src/ModbusTCPTemplate.h#L272-L276
and reused for calculating the size of the response packet:
https://github.com/emelianov/modbus-esp8266/blob/299666307a052df52f757f3131e292c2513bb57f/src/ModbusTCPTemplate.h#L336-L343

The exception code gets lost in that process.

Also   https://github.com/emelianov/modbus-esp8266/blob/299666307a052df52f757f3131e292c2513bb57f/src/ModbusTCPTemplate.h#L275
is only dropping 1 byte because of `_len` always being `1` at this point

**Comment by emelianov** [comment]
Fixed in 644c3245cc2ef3f2e515c4fa538e9c2e3573b232
