### ISSUE TITLE
Multiple holding register reads with overlapping addresses

### ISSUE THREAD

**Issue by roelof4** [emelianov/modbus-esp8266#271]
Take the case of a consecutive range of holding registers, say 100 ... 109. My Modbus client would like to make two types of multiple register reads, one to only read the first two holding registers (100 and 101) and another one to read all 10 holding registers.
How do I setup the correct addHreg and call back functions in this case?

**Comment by emelianov** [comment]
onGet/onSet callbacks executed for each individual registers. Than meant the library internally interprets request and execute callback for each register affected.
