### ISSUE TITLE
Dead link on https://github.com/emelianov/modbus-esp8266/tree/master/examples/TCP-ESP

### ISSUE THREAD

**Issue by JimKnopf1503** [emelianov/modbus-esp8266#272]
Hi!

The link on the page https://github.com/emelianov/modbus-esp8266/tree/master/examples/TCP-ESP labled as "Server" is dead.
Linked to https://github.com/emelianov/modbus-esp8266/blob/master/examples/TCP-ESP/server.ino.

Burkhard

**Comment by rob040** [comment]
Indeed, the first three links in [examples/TCP-ESP/README.md](https://raw.githubusercontent.com/emelianov/modbus-esp8266/master/examples/TCP-ESP/README.md) missing and extra indirection, as required by Arduino IDE:
in README.md, change
` (client.ino)`
to
` (client/client.ino)`

`  (clientSync.ino)`
to
`  (clientSync/clientSync.ino)`

`  (server.ino)`
to
`  (server/server.ino)`
