### ISSUE TITLE
Sensor data through Modbus RTU protocol

### ISSUE THREAD

**Issue by sriinii** [emelianov/modbus-esp8266#284]
Could you help us with the code for slave to send the sensor data to the master through the Modbus Protocol.

**Comment by jpily** [comment]
Please post the full code that reads from slave. I'll explain it accordingly.

**Comment by AlHasanSameh** [comment]
> Please post the full code that reads from slave. I'll explain it accordingly.

Hi, can you please help me with my issue, the library author doesn't seem to respond or explain 
https://github.com/emelianov/modbus-esp8266/issues/283
