### ISSUE TITLE
I am facing Read and Write issue in register

### ISSUE THREAD

**Issue by testgithubesp** [emelianov/modbus-esp8266#286]
In case of reading holding registers (using RTU >> MasterSync code) the request-response we get the same for all register address i.e, 0xE4112. And please suggest which library code is used for write data to the registers. The same example code i have modified and same is attached to the mail for your reference.

[masterSync.zip](https://github.com/emelianov/modbus-esp8266/files/11295502/masterSync.zip)

**Comment by emelianov** [comment]
0xE4 -- it's timeout error that typically caused by wiring errors
