### ISSUE TITLE
simple RTU slave example

### ISSUE THREAD

**Issue by Vorms** [emelianov/modbus-esp8266#288]
Hello,
Many thanks for your library,
Can you add a complete slavec RS485 RTU example with at least readcoil example ?
The example you put is to minimalist...

Many thanks for your help and regards

**Comment by emelianov** [comment]
There is really complete slave example. That's really all code needed to implement ModbusRTU slave.
https://github.com/emelianov/modbus-esp8266/blob/master/examples/RTU/slave/slave.ino

**Comment by pkrssy** [comment]
Does slave handle incoming writes from master (eg. 0x06 - Write Single Register) if a register is added with mb.addHreg(REGN)? If so, how to set RW status of "REGN"?
