### ISSUE TITLE
Device Connected, but "MODBUS Exception Response from Slave Device" at Modscan

### ISSUE THREAD

**Issue by arimukhlas** [emelianov/modbus-esp8266#289]
Hi @emelianov  thanks for great library

I'm trying based on [sample Library ](https://github.com/emelianov/modbus-esp8266/blob/ea2bd0e506b2c32755ca86edcd2ea95acc1b0855/examples/TCP-ESP/IP-server-AnalogInput/IP-server-AnalogInput.ino) 
```c++
#ifdef ESP8266
 #include <ESP8266WiFi.h>
#else //ESP32
 #include <WiFi.h>
#endif
#include <ModbusIP_ESP8266.h>

//Modbus Registers Offsets
const int SENSOR_HREG = 100;

//ModbusIP object
ModbusIP mb;

long ts;

void setup() {
    Serial.begin(115200);

    WiFi.begin("MySSID", "MyPass");
    while (WiFi.status() != WL_CONNECTED) {
        delay(500);
        Serial.print(".");
    }

    Serial.println("");
    Serial.println("WiFi connected");  
    Serial.println("IP address: ");
    Serial.println(WiFi.localIP());

    mb.server();		//Start Modbus IP
    // Add SENSOR_HREG register - Use addHreg()
    mb.addHreg(SENSOR_HREG);

    ts = millis();
}

void loop() {
   //Call once inside loop() - all magic here
   mb.task();

   //Read each two seconds
   if (millis() > ts + 2000) {
       ts = millis();
       //Setting raw value (0-1024)
       mb.Hreg(SENSOR_HREG, 5);
   }
   delay(10);
}
``` 

after upload sketch, esp got IP 192.168.43.224

![image](https://user-images.githubusercontent.com/95061616/235591567-21c74a28-91c4-41b4-8c14-d461d4595f23.png)

Then I try to see the data value using Modscan Software

![image](https://user-images.githubusercontent.com/95061616/235591657-80e7a869-63ba-423c-ae37-d2b6ea584aa9.png)

but I dont see the data value

![image](https://user-images.githubusercontent.com/95061616/235591823-4c459cdb-44e5-42c0-b932-cf2ebfa25b80.png)

Is my procedure correct, or something I miss?
How to see data value on Modscan? Thanks

**Comment by Merdock1** [comment]
With this code, I get results without problems
[https://github.com/Merdock1/DataConversion/blob/main/src/Examples/ExampleAll.ino](https://github.com/Merdock1/DataConversion/blob/main/src/Examples/ExampleAll.ino)


![Capture](https://github.com/emelianov/modbus-esp8266/assets/55119965/630c5e39-2443-4e5e-b1b0-69debac9a03f)

**Comment by Merdock1** [comment]
I think your problem is in the number of records, your code only has one holding record at position 100 and you ask the software to read 10 records from position 100, I think that is the reason for your error, you must tell it to read 1 register at position 100
