### ISSUE TITLE
how to read modbusTCP slave device with modbusTCP Master On ESP8266

### ISSUE THREAD

**Issue by aandrie77** [emelianov/modbus-esp8266#291]
Hi, may i ask to this? how to read slave ModbusTCP device with Library ModbusTCP Master on ESP8266 ? Read value Slave ModbusTCP Device? and can used specif for ID Device Slave like this attachment image

![modbusTCP multiID](https://github.com/emelianov/modbus-esp8266/assets/6893085/c14b82fb-0b3b-4c38-a686-f06a927bae51)

**Comment by emelianov** [comment]
In terms of ModbusTCP slave_id is unit_id (last argument):
```c
uint16_t readCoil(IPAddress ip, uint16_t offset, bool* value, uint16_t numregs = 1, cbTransaction cb = nullptr, uint8_t uint = MODBUSIP_UNIT);
```
