### ISSUE TITLE
SSL support in modbus TCP

### ISSUE THREAD

**Issue by tarnak** [emelianov/modbus-esp8266#303]
Hi Sir,

Is there any chance to implement SSL in modbus tcp layer?
Maybe compatible with https://github.com/OPEnSLab-OSU/SSLClient which supposed to be multiplatfom

Thanks,
Chris

**Comment by emelianov** [comment]
Modbus Security is already supported by library. Just keep in mind target platform initiations.
https://github.com/emelianov/modbus-esp8266/tree/master/examples/TLS
