### ISSUE TITLE
Is it possible to build a modbus rtu gateway/multiplexer?

### ISSUE THREAD

**Issue by tobox** [emelianov/modbus-esp8266#304]
In several installations, there are several modbus masters that want to read the main power meter, e.g. electric car charger, heat pump, solar inverter, battery inverter... My electrician says I need separate modbus meters for each modbus master. 

Would it be possible with this library to build a device with several modbus client ports, that would forward the requests over a single modbus server port to a physical modbus meter (and then send the responses back to the originating port)?

**Comment by emelianov** [comment]
Sure.
The library instances on single device is limited just by hardware. There is [examples](https://github.com/emelianov/modbus-esp8266/tree/master/examples/Bridge) on how to build bridges.
