### ISSUE TITLE
RTU Slave with auto reading of registers

### ISSUE THREAD

**Issue by TheStranger25** [emelianov/modbus-esp8266#307]
Hi all, I've just started working with this library and so far I've managed to set the slave id, its registers and the values of each register very easily. 
Now I need to be able to check the value of a register to see if it has been changed by a master, but if you run slave(id) in setup, it will never go inside the if (!mb.slave()). Here is my code, thanks in advance:

```
ModbusRTU mb;

void CheckInfoUpdate(){
  uint16_t res[1];  
  if (!mb.slave()) {    // Check if no transaction in progress
    mb.readHreg(id, "zero", res);
    while(mb.slave()) { // Check if transaction is active
      mb.task();
      delay(10);
    }
  }  
  return;
}

void Setup(){
  mb.begin(&Serial, 16, true);
  mb.setBaudrate(MyConf.GetBaudRate());
  mb.slave(id);
  mb.addHreg("zero");
  mb.Hreg("zero",0);
  mb.addHreg("one"); //0
  mb.addHreg("two");
  mb.addHreg("three");
}

void Loop(){
  if ((millis() - this->TimeToCheckUpdate) > 500){
    CheckInfoUpdate();
    this->TimeToCheckUpdate = millis();
  } else {
    mb.task();
    yield();
  }
}

```

**Comment by emelianov** [comment]
For the first it's interesting approach to pass a string as register id (that is integer indeed).
As for question itself, you can use `uint16_t value = mb.Hreg(register_id);` to read current register value.
