### ISSUE TITLE
missing StreamBuf library Error

### ISSUE THREAD

**Issue by coskunergan** [emelianov/modbus-esp8266#311]
..\AppData\Local\Temp\.arduinoIDE-unsaved202396-6128-pcq1an.1gml\TCP-to-RTU-Simulator\TCP-to-RTU-Simulator.ino:14:10: fatal error: StreamBuf.h: No such file or directory
   14 | #include <StreamBuf.h>
      |          ^~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: StreamBuf.h: No such file or directory

Somebody can help me plz.

How can i fix?

**Comment by emelianov** [comment]
https://github.com/emelianov/StreamBuf
