### ISSUE TITLE
help needed : how can i distinguish the callbacks at modbusRTU

### ISSUE THREAD

**Issue by Q7Jensen** [emelianov/modbus-esp8266#312]
If I have something like that
`case 0:`
`  result = mbRTU.readHreg(SLAVE_ID, 0, res, REG_COUNT, cbReadRTU); // voltage`
`  break;`
`case 1:`
`  result = mbRTU.readHreg(SLAVE_ID, 6, res, REG_COUNT, cbReadRTU); // current`
`  break`;
and
`bool cbReadRTU(Modbus::ResultCode event, uint16_t transactionId, void* data) { `
`  if (event != Modbus::EX_SUCCESS) {`
`    Serial.printf_P("Request result from callback: 0x%02X", event);  }`
`  else {`
`    // voltage or current ?`
`  }`
`  return true;`
`}`

How can I distinguish the callbacks?
Do I need different callbacks?
BR Jens

**Comment by emelianov** [comment]
https://github.com/emelianov/modbus-esp8266/issues/165
