### ISSUE TITLE
Debug ModbusTCP data received

### ISSUE THREAD

**Issue by matiasbarone** [emelianov/modbus-esp8266#320]
Im getting ILLEGAL_VALUE when I try to read a Hreg with readHreg function. Im ussing a modbusTCP conecction and readwrite function work fine.

There's a way to get the raw dataframe received? to analyze the data received.

Thanks

**Comment by emelianov** [comment]
Uncomment `#define MODBUSIP_DEBUG` in `ModbusSettings.h`
