### ISSUE TITLE
#define MODBUSRTU_DEBUG seems to have no effect when defined outside ModbusSettings.h

### ISSUE THREAD

**Issue by fredlcore** [emelianov/modbus-esp8266#322]
I wanted to turn on debug messages and thus added `#define MODBUSRTU_DEBUG` before `#include <ModbusRTU.h>`.
However, this does not seem to have any effect. Only if I enable the definement in ModbusSettings.h it will take effect. Do I do anything wrong here?

**Comment by 14yannick** [comment]
Same for me did found a solution

**Comment by emelianov** [comment]
It's works so by C/CPP design

**Comment by fredlcore** [comment]
You're right, thanks for the explanation.
