### ISSUE TITLE
Does this library allow MODBUS/TCP Security over ethernet using an ethernet shield?

### ISSUE THREAD

**Issue by rafaelkai** [emelianov/modbus-esp8266#333]
As the title says, I would like to implement a Modbus TCP Security client and send data over Ethernet using an Ethernet shield instead of ESP8266/ESP32 and WiFi.

**Comment by emelianov** [comment]
https://github.com/espressif/arduino-esp32/blob/master/libraries/Ethernet/examples/ETH_W5500_IDF_SPI/ETH_W5500_IDF_SPI.ino

The library code just as for WiFi
