### ISSUE TITLE
Reference to holding register

### ISSUE THREAD

**Issue by bvtvusn** [emelianov/modbus-esp8266#334]
This is a great library!
Is it possible to get a reference or pointer to the modbus slave array that is used behind the scenes in the library?
The idea is that I want to make a new variable that points directly to the memory location where the library stores the states of the holding registers.
This way, I don't have to call mb.Hreg() every loop.
It would also make it easier to transfer floating point values directly over modbus.

Thank you.

**Comment by emelianov** [comment]
Internally registers stored objects in <variant> or custom equivalent (depending on Arduino board used) so it's not possible to provide access you want.
You can use `onGet` callback dynamically to return custom data on register query no setting the value.
