### ISSUE TITLE
Slave timeout?

### ISSUE THREAD

**Issue by RosiersRobin** [emelianov/modbus-esp8266#343]
Hi,

I'm trying to write a slave (client) device, but I seem to have some trouble...

Currently the simple Modbus client example (found here https://github.com/emelianov/modbus-esp8266/blob/master/examples/RTU/slave/slave.ino ) doesn't seem to work for me either? I keep getting "no response from slave".

This CAN be an hardware issue, but not really certain about it...

I'm using a macbook pro M3 with ModbusRtuMaster application.

Any help is appreciated!

**Comment by emelianov** [comment]
Most likely wiring problem.
On esp's rs-485 transceiver side make sure you are using auto rx-tx type or re-de are properly connected.
On Mac side check usb-ttl chip is fully supported.
