### ISSUE TITLE
modbusRTU issues

### ISSUE THREAD

**Issue by janniebunny** [emelianov/modbus-esp8266#347]
Hi there,
I have been using serial and ESP32 IP modbus for this library for years. Now nothing works. I am not an expert, simply a maker. How is it possible that it is somehow better when I have tried everything to make it work? It is really frustrating. I am not a power user and simply want to communicate with my hardware the way I used. No fancy stuff. I find it near impossible to even try and find the issue. 

All I want to do is setup registers and read/write them.

If I use serial, I use USB-serial, no TxRx pins.

Can anyone show me a sketch for Serial modbus WITHOUT tranmission pins? Thank you.

Regards
Jan

**Comment by emelianov** [comment]
USB-Serial should be used with Serial-RS485 modules with auto RX/TX switching.
