### ISSUE TITLE
Ignore Callbacks when Register is Updated by Self

### ISSUE THREAD

**Issue by seikosantana** [emelianov/modbus-esp8266#352]
Hi, is there a way to update register value without triggering the onSetCoil / onSetHreg?
I am trying to integrate modbus into existing working program so that it can interface with modbus, but the problem is when I use onSetCoil/onSetHreg to handle incoming requests, and have my program to update the registers to represent the current state, it fires the callbacks too, causing recursive calls or long loops.

Do you have any tips or workarounds for this kind of situation? Thanks in advance

**Comment by emelianov** [comment]
```c
mb.cbDisable();
mb.Hreg(REV, VALUE);
mb.cbEnable();
```

Or safer variant
```cpp
bool saved_state = mb.cbEnable(false);
mb.Hreg(REV, VALUE);
mb.cbEnable(saved_state);
```

**Comment by seikosantana** [comment]
Is it safe to call those in a callback itself (inside an onSet)?

**Comment by emelianov** [comment]
Sure.

**Comment by seikosantana** [comment]
Thanks a lot for your response and effort on the library 😀
