### ISSUE TITLE
How to write multiple coil

### ISSUE THREAD

**Issue by Soft-Eng-Soft** [emelianov/modbus-esp8266#362]
Hi emelianov
How to write multiple coil

**Comment by Minosoft1510** [comment]
Hey, I have the same issue too. When trying to Write multible Coils in sequence to different Slaves it only does the first one. what am i doing wrong?

void loop() {
if (!mb.slave()) {
      mb.writeCoil(1, 1, coils[1], cbWrite);
      mb.writeCoil(2, 1, coils[2], cbWrite);
 }
mb.task();
delay(25);
}
