### ISSUE TITLE
TCP-ESP client problem

### ISSUE THREAD

**Issue by Ntranx** [emelianov/modbus-esp8266#363]
I am using the default example client.ino, I load it with my Wifi network and the server address (I have the server on my PC with modbus slave) similar to this video https://www.youtube.com/watch?v=y1URgaKtmAI
but I try and try and I don't get any response from the slave or any changes, I already tried to write, read and nothing

**Comment by emelianov** [comment]
Can you provide extra information? Do you mean timeout error under "no response"? Can you get response on ping of ESP device?
