### ISSUE TITLE
Arduino Uno & GPRS Shield Uno & Modbus

### ISSUE THREAD

**Issue by C4ORT** [emelianov/modbus-esp8266#367]
Hello! I apologize that I am not strong enough in this topic, so I want to ask knowledgeable people.
Can I use this library to connect my device (consisting of Arduino Uno, GPRS Shield Uno and a temperature sensor) to the OPS server? I found a lot of information about working via an Ethernet connection, but not via GPRS (Internet access via a SIM card)
I was able to establish a connection to the server via TSP/IP and transfer data there via an HTTP request
Can you help with an example? Or give something worth looking at
Thanks!

PS: I used a translator, sorry if something is wrong

**Comment by emelianov** [comment]
Can you provide details on TCP library used for the GPRS Shield. Probably their functionality limited to http or some specific implementation is required (as the Modbus library has only Ethernet library support for generic Arduino).
