### ISSUE TITLE
Read a 32bit value

### ISSUE THREAD

**Issue by ltonini80** [emelianov/modbus-esp8266#37]
Hi, i need to read a 32bit value (2 reg of 16 bit) with the second reg is the lower value and first is the high value from tcp device that have uid = 3.
I use mb.readHreg(remote, REG_POWER, (uint16_t*)&prodPower32_W, 2, nullptr, 3); but prodPower32_W return =0.
Can you help me?
Thank you

**Comment by emelianov** [comment]
Hello,
Can you share code you are using ?
