### ISSUE TITLE
Unable to get response with Modbus poll and ESP32 (as a RTU slave)

### ISSUE THREAD

**Issue by heroseller17** [emelianov/modbus-esp8266#42]
Hello,
First of all thank you for the library ,i think it's a detailed library.

I,m using ESP32 with arduino IDE .I try to use RTU_SLAVE.ino with UART2.I design a board and connect GPIO16,17 (Uart 2) to MAX3485 .but this examlpe doesn't work.what is the problem?
here is my code i just change the uart:
`
#include <ModbusRTU.h>

#define REGN 10
#define SLAVE_ID 1

ModbusRTU mb;

void setup() {
  Serial2.begin(9600, SERIAL_8N1);
  mb.begin(&Serial2);
  mb.slave(SLAVE_ID);
  mb.addHreg(REGN);
  mb.Hreg(REGN, 100);

}

void loop() {
  mb.task();
  yield();
}`

**Comment by emelianov** [comment]
Hello,
You'r welcome.

Additional you need to control send/receive. Wire MAX's DE and RE to, say, pin 18 and use
```c
mb.begin(&Serial2, 18);
```
