### ISSUE TITLE
Usage of std:function / std::bind

### ISSUE THREAD

**Issue by lazyweirdo** [emelianov/modbus-esp8266#49]
Hello, first of all the library is great ... it saved me hours of hard work
The only thing i wasn't able to figure out how to handle is about the way cbTransaction is declared
```cpp
typedef bool (*cbTransaction)(Modbus::ResultCode event, uint16_t transactionId, void* data); // Callback skeleton for requests
```
I work with classes/objects, in fact this library too, but i was not able to use an object method as cbTransaction callback. I used to work with std:function and std::bind for this pourpose.
I do something like this when working with callbacks:
```cpp
this->onReadCallback = std::bind(&MyClass::onRead, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3);
this->modbus = new ModbusRTU();
// modbus initialization ... bla bla
// then ...
this->modbus->readHreg(1, 300, this->regValue, 1, this->onReadCallback);
```
Is there any way to do it with the current declaration/definition of cbTransaction ?

Thanks

**Comment by emelianov** [comment]
Hello @lazyweirdo,
I'm afraid with current implementation it's not possible to use class memebers as callbacks.
You have to use standalone wrapper function.
