### ISSUE TITLE
question about other MCUs

### ISSUE THREAD

**Issue by kevin192291** [emelianov/modbus-esp8266#61]
I know this is really outside of the scope of this library, but I am just wondering
if you know if this would be easy to port to the Microchip SAMR MCUs?

**Comment by emelianov** [comment]
Hello Kevin,
Currently ModbusRTU can be build for Arduino's various architectures (STL is required).

Also there is development version of complete support of ModbusRTU and ModbusTCP for  most of Arduino boards (with no STL). You may test it from [4.0.0](https://github.com/emelianov/modbus-esp8266/tree/4.0.0) branch.
