### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by workpage2** [emelianov/modbus-esp8266#68]
I am trying to use your library for my esp32 code.
When trying to connect, I get this error:

    assertion "heap != NULL && "free() target pointer is outside heap areas"" failed: file "/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/heap/heap_caps.c", line 267, function: heap_caps_free
    abort() was called at PC 0x401512af on core 1

    Backtrace: 0x4008c7bc:0x3ffb1d40 0x4008c9ed:0x3ffb1d60 0x401512af:0x3ffb1d80 0x40084b57:0x3ffb1db0 0x400850b9:0x3ffb1dd0 0x4000bec7:0x3ffb1df0 0x400fca43:0x3ffb1e10 0x400d9bee:0x3ffb1e50 0x400fefb9:0x3ffb1fb0 0x40088d1d:0x3ffb1fd0

    Rebooting...

Sometimes the error is like this:

    Guru Meditation Error: Core  1 panic'ed (InstrFetchProhibited). Exception was unhandled.
    Core 1 register dump:
    PC      : 0x00000075  PS      : 0x00060630  A0      : 0x800d9bf1  A1      : 0x3ffb1e10  
    A2      : 0x3ffc1e74  A3      : 0x00000075  A4      : 0x3ffceba8  A5      : 0x00000000  
    A6      : 0x00000000  A7      : 0x3ffb1e10  A8      : 0x800fc8d3  A9      : 0x3ffb1df0  
    A10     : 0x3ffb1e28  A11     : 0x3ffceba8  A12     : 0xa8f56be9  A13     : 0x00000001  
    A14     : 0x3ffc2430  A15     : 0x3ffb0060  SAR     : 0x0000000a  EXCCAUSE: 0x00000014  
    EXCVADDR: 0x00000074  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000  
    
    Backtrace: 0x00000075:0x3ffb1e10 0x400d9bee:0x3ffb1e50 0x400fefb9:0x3ffb1fb0 0x40088d1d:0x3ffb1fd0
    
    Rebooting...

communication is present for 1-2 seconds after modbus connection is established. If you add delay (10) then the connection will be 15 seconds. Then an error and a reboot.. When there is no connection, the program works and there is no error.
I made labels in the program. The error occurs when the
 mb.task () ;.
My program is large and complex. Uses webserver, mqtt, websocket, HTTPClient.h
p.s. IP-server-HoldingReg works fine.

**Comment by emelianov** [comment]
On that limited information can only suspect that problem is about multitasking.
The Mobbus library is not thread-safe so if you calling modbus methods from different threads without external semaphore locking it will crash sooner or later.
Otherwise addintional info is required to identify the issue.

**Comment by workpage2** [comment]
Александр, вы оказывается мой земляк!
Вобщем проблема была как в том анекдоте про лом и ботинки.
Что бы отправить данные в websocket, нужно преобразовать переменную и string в charArray. Для этого используется промежуточная переменная char data1[]. Я указал слишком маленькую длину. После увеличения размера data1 библиотека modbus падать перестала!
Спасибо за Ваш труд. Отличная библиотека!

    data_temp="╚23"+ntp_adr;
    data_temp.toCharArray(data1,(data_temp.length()+1));
    webSocket.broadcastTXT(data1,data_temp.length());

**Comment by emelianov** [comment]
Мир тесен, Владимир ;).
Отдаю долг OpenSource'у, так сказать. + Даже иногда донаты прилетают, но не окупают время, конечно.
Glad the problem have resolved.

**Comment by workpage2** [comment]
Куда донатить? Дайте ссылку или карту.

**Comment by emelianov** [comment]
|If the library is helpful for your projects you can support it by a glass of beer|[![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=Z38SLGAKGM93S&source=url)|
|---|---|

Уже вставил ссылку, но вспомнил, что внутри России PayPal теперь person-to-person не переводит.
Можно через систему быстрых платежей на номер +7-912-922-7-666 (Альфа)
