### ISSUE TITLE
Using only ModbusRTU on PlatformIO

### ISSUE THREAD

**Issue by TSO-tech** [emelianov/modbus-esp8266#69]
Hi,

I'm using the lib on VSC with PlatformIO to create a simple sensor with modBus RTU (salve).

on file platformio.ini I have "lib_deps = melianov/modbus-esp8266 @ ^3.0.3"

on main.cpp (renamed RTU-slave.ino) I only reference is to #include <ModbusRTU.h> but I always get compiler error on file ModBusIP_ESP8266.cpp.

To solve the compiler error I have to delete ModBusIP_ESP8266.h and ModBusIP_ESP8266.cpp.
There is any change I have to do?

thanks

**Comment by gonzabrusco** [comment]
You could try changing the way PlatformIO scans for libraries. 

    lib_ldf_mode = deep

More info: https://docs.platformio.org/en/latest/librarymanager/ldf.html

**Comment by TSO-tech** [comment]
Hi @gonzabrusco,

Thank you for your reply. I'm new to PlatformIO and my programing skills are limited (I didn't program anything for years) So I have some difficulty to understand the full impact of the options. 

The initial suggestion didn't work, but using the lib_ldf_mode = deep+ worked. I'm assuming the main difference is taking in consideration C/C++ Preprocessor conditional syntax.
