### ISSUE TITLE
Stop modbusIP or modbusRTU

### ISSUE THREAD

**Issue by gonzabrusco** [emelianov/modbus-esp8266#75]
Hello. I'm looking for a way to stop a modbusIP or modbusRTU object. Both libraries have a "start" method but none have an stop method. I know I could just destroy them, but after reviewing the code I can see you don't stop the WiFiServer on the ModbusIP library. Is that ok? Shouldn't the "tcpserver" be destroyed? 

```
void ModbusIP::server(uint16_t port) {
	serverPort = port;
	tcpserver = new WiFiServer(serverPort);
	tcpserver->begin();
}
```

```
ModbusIP::~ModbusIP() {
	free(_frame);
	dropTransactions();
	cleanupConnections();
	cleanupTransactions();
	for (uint8_t i = 0; i < MODBUSIP_MAX_CLIENTS; i++) {
		delete tcpclient[i];
		tcpclient[i] = nullptr;
	}
}
```

Also, the global regs are set as global variables, would not be a good idea to have them as STATIC inside the Modbus class?

**Comment by emelianov** [comment]
Thanx.
Destructor fixed.
_resg, _callbacks marked static.
Pushed to master branch.
