### ISSUE TITLE
Проблема с использованием функций pullXXXX (считывание регистров очереди)

### ISSUE THREAD

**Issue by pavelchun** [emelianov/modbus-esp8266#77]
Если использовать #define MODBUSRTU_ADD_REG, То локально создается только один регистр из запрошенных, т.к. вызывается функция addIreg(to, numregs). А она принимает значения addIreg(uint16_t offset, uint16_t value, uint16_t numregs).

И по остальным pullXXXX также. Соответственно при считывании в локальные регистры записывается только первый.

В частности в modbusRTU точно проверено, в modbusTCP глазами тоже самое видно (не проверено).

**Comment by emelianov** [comment]
Спасибо.
Исправлено. Запушено в master.
