### ISSUE TITLE
error compilling RTU modbus conection

### ISSUE THREAD

**Issue by lucasrebra** [emelianov/modbus-esp8266#89]
When I compile the RTU Master program example in PlatformIO I get an error like this:
.pio\libdeps\esp32doit-devkit-v1\modbus-esp8266\src\ModbusIP_ESP8266.h:14:19: fatal error: WiFi.h: No such file or directory

When I include the Wifi.h library it disappears, but I don't know if that could be correct or there's something that is working wrong on the RTU modbus library. The TCP library is perfect and I have worked a lot with it without any problems. 

Thank you

**Comment by emelianov** [comment]
Probably that's because of the way how Platformio builds dependent libraries. Your workaround is ok an don't lead to any memory footprint overhead.
