### ISSUE TITLE
Modbus RTU 

### ISSUE THREAD

**Issue by Warlib1975** [emelianov/modbus-esp8266#9]
Hello,

do you plan to make Modbus RTU support? I couldn't find a stably working library.

**Comment by emelianov** [comment]
Sure. But as the library is a pet project timeframe is undefined.

**Comment by emelianov** [comment]
Take a look first draft of ModbusRTU implementation.
https://github.com/emelianov/modbus-esp8266/tree/devel

**Comment by emelianov** [comment]
ModbusRTU now is available in master branch.

**Comment by Warlib1975** [comment]
Thank you. :-) I'll test.
