### ISSUE TITLE
Callback double call

### ISSUE THREAD

**Issue by skirchev** [emelianov/modbus-esp8266#91]
Hello Emelianov,
Very useful library. Unfortunately I got into an issue with the callbacks. Function __bswap_16 leads to double call of Reg function. Thus calls the callback twice. It could be a specific compiler related, but I just decided to make you aware of that.
(Used Arduino 1.8.13)

Thanks for the wonderful work!

**Comment by emelianov** [comment]
Thanks.
It was a bug. [Fixed](../releases/3.0.6)
