### ISSUE TITLE
schema of ESP8266 - max485 connection

### ISSUE THREAD

**Issue by rzylius** [emelianov/modbus-esp8266#92]
Would it be possible to provide schematics of the connecting ESP to ModbusRTU device? it is not obvious from current documentation.

**Comment by yashp96** [comment]
![20201210_153130.jpg](https://user-images.githubusercontent.com/42352174/101757555-4abd7800-3afd-11eb-828b-983366a79a93.jpg) this is for ESP32 but you can follow the same for ESP8266. Just different GPIOs and softwareserial for ESP8266.

**Comment by rzylius** [comment]
Thank you!
