### ISSUE TITLE
'ModbusReadCallBack' was not declared in this scope

### ISSUE THREAD

**Issue by yashp96** [emelianov/modbus-esp8266#93]
I am using the library along with **PubSubClient.** I am calling read holding register function (readHreg) inside of MQTT Subscription callback function. When I compile the code, the compiler throws **'ModbusReadCallBack' was not declared in this scope** . Can I know why am I getting this error? Any help is appreciated. Thank You!

Update:
I tried compiling my code in Arduino IDE. It Compiles code without any error. I get the mentioned error in Visual Studio's vMicro Plugin. Any idea why?

**Comment by emelianov** [comment]
It looks like `ModbusReadCallBack` your own function. I think creating header file for the function and including it to problematic module should help.

**Comment by yashp96** [comment]
Not sure what is/was the exact problem, but restarting Visual Studio seems to solve it. I will try your suggestion as well. I posting screen shot and closing the issue.
Thank You Sir!
![image](https://user-images.githubusercontent.com/42352174/101866217-47c69400-3b9e-11eb-95a9-88697d25e094.png)
![image](https://user-images.githubusercontent.com/42352174/101866265-5f058180-3b9e-11eb-83fd-213aae73e6d5.png)
